coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 2%
        only_pulls: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
