///////////////////////////////////////////////////////////////////////////////////////
///////// > openSMILE configuration file, Geneva feature set <       //////////////////
/////////   Modified for external audio input (R package integration) //////////////////
///////// (c) 2014, 2020 by audEERING                                //////////////////
/////////     All rights reserved. See file COPYING for details.     //////////////////
///////////////////////////////////////////////////////////////////////////////////////

;;;;;;; component list ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[dataMemory].type=cDataMemory
printLevelStats=0

;;;;;;;;;;;;;;;;;;;;;;;;;;;; External audio input ;;;;;;;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[externalAudio].type=cExternalAudioSource

[externalAudio:cExternalAudioSource]
writer.dmLevel=wave
sampleRate=16000
channels=1
nBits=16
blocksize=70000
fieldName=pcm

;;;;;;;;;;;;;;;;;;;;;;;;;;;; Processing chain ;;;;;;;;;;;;;;;;;;;;;;;;;;;

\{GeMAPSv01b_core.lld.conf.inc}
\{GeMAPSv01b_core.func.conf.inc}

;;;;;;;; prepare for external data sink ;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[lldconcat].type=cVectorConcat
instance[funcconcat].type=cVectorConcat
instance[functionals].type=cExternalSink

[lldconcat:cVectorConcat]
reader.dmLevel = gemapsv01b_lldsetE_smo;gemapsv01b_lldsetF_smo
writer.dmLevel = lld
includeSingleElementFields = 1

[funcconcat:cVectorConcat]
reader.dmLevel = gemapsv01b_functionalsF0;gemapsv01b_functionalsLoudness;gemapsv01b_functionalsMeanStddevVoiced;gemapsv01b_functionalsMeanSpectralUnvoiced;gemapsv01b_temporalSet
writer.dmLevel = func
includeSingleElementFields = 1

[functionals:cExternalSink]
reader.dmLevel = func
