test_that("trk_iaif_vat returns sample-rate glottal flow + derivative", {
  skip_if_not_installed("voiceanalysis")
  wav <- system.file("samples/sustained/a1.wav", package = "superassp")
  skip_if(wav == "", "a1.wav not bundled")
  obj <- trk_iaif_vat(wav, toFile = FALSE)
  expect_s3_class(obj, "AsspDataObj")
  expect_named(obj, c("glottal_flow", "glottal_derivative"))
  expect_equal(attr(obj, "trackFormats"), c("REAL64", "REAL64"))
  expect_equal(nrow(obj$glottal_flow), nrow(obj$glottal_derivative))
  expect_true(all(is.finite(obj$glottal_flow)))
  expect_true(all(is.finite(obj$glottal_derivative)))
})

test_that("trk_iaif_vat output correlates with trk_covarep_iaif (sanity)", {
  skip_if_not_installed("voiceanalysis")
  wav <- system.file("samples/sustained/a1.wav", package = "superassp")
  skip_if(wav == "", "a1.wav not bundled")
  v <- trk_iaif_vat(wav, toFile = FALSE)
  c_obj <- tryCatch(trk_covarep_iaif(wav, toFile = FALSE), error = function(e) NULL)
  skip_if(is.null(c_obj), "trk_covarep_iaif unavailable")
  n <- min(nrow(v$glottal_derivative), nrow(c_obj$glottal_derivative))
  # Trim 5% off each end (boundary effects differ between implementations)
  trim <- round(0.05 * n)
  idx <- seq(trim, n - trim)
  expect_gt(abs(cor(v$glottal_derivative[idx, 1], c_obj$glottal_derivative[idx, 1])), 0.5)
})
