///////////////////////////////////////////////////////////////////////////////////////
///////// > openSMILE configuration file, eGeMAPS feature set <      //////////////////
/////////   Modified for external audio input (R package integration) //////////////////
///////// (c) 2014, 2020 by audEERING                                //////////////////
/////////     All rights reserved. See file COPYING for details.     //////////////////
///////////////////////////////////////////////////////////////////////////////////////

;;;;;;; component list ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[dataMemory].type=cDataMemory
printLevelStats=0

;;;;;;;;;;;;;;;;;;;;;;;;;;;; External audio input ;;;;;;;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[externalAudio].type=cExternalAudioSource

[externalAudio:cExternalAudioSource]
writer.dmLevel=wave
sampleRate=16000
channels=1
nBits=16
blocksize=70000
fieldName=pcm

;;;;;;;;;;;;;;;;;;;;;;;;;;;; Processing chain ;;;;;;;;;;;;;;;;;;;;;;;;;;;

\{GeMAPSv01b_core.lld.conf.inc}
\{eGeMAPSv02_core.lld.conf.inc}
\{GeMAPSv01b_core.func.conf.inc}
\{eGeMAPSv02_core.func.conf.inc}

;;;;;;;; prepare for external data sink ;;;;;;;;;;;;;;;;;;;;;

[componentInstances:cComponentManager]
instance[lldconcat].type=cVectorConcat
instance[funcconcat].type=cVectorConcat
instance[functionals].type=cExternalSink

[lldconcat:cVectorConcat]
reader.dmLevel = egemapsv02_lldsetE_smo;egemapsv02_lldsetF_smo
writer.dmLevel = lld
includeSingleElementFields = 1

[funcconcat:cVectorConcat]
reader.dmLevel = gemapsv01b_functionalsF0;gemapsv01b_functionalsLoudness;egemapsv02_functionalsMeanStddevZ;egemapsv02_functionalsMeanStddevVoiced;egemapsv02_functionalsMeanUnvoiced;gemapsv01b_temporalSet;egemapsv02_leq
writer.dmLevel = func
includeSingleElementFields = 1

[functionals:cExternalSink]
reader.dmLevel = func
