
import os
import numpy as np
import sys
import parselmouth
from parselmouth.praat import call

PATH = os.path.dirname(os.path.realpath(__file__))

sys.path.append(PATH)

def multi_find(s, r):
	"""
	Internal function used to decode the Formants file generated by Praat.
	"""
	s_len = len(s)
	r_len = len(r)
	_complete = []
	for i in range(s_len):
		# search for r in s until not enough characters are left
		if s[i:i + r_len] == r:
			_complete.append(i)
		else:
			i = i + 1
	return _complete

def praat_vuv(audio_filaname, resultsp, resultst, time_stepF0=0, minf0=75, maxf0=600, maxVUVPeriod=0.02, averageVUVPeriod=0.01):
	"""
	Uses Parselmouth to obtain pitch and voicing decisions for a wav file.
	It writes the results into two text files, one for the pitch and another
	for the voicing decisions. These results can then be read using the function
	read_textgrid_trans and decodeF0

	:param audio_filaname: Full path to the wav file
	:param resultsp: Full path to the resulting file with the pitch
	:param resultst: Full path to the resulting file with the voiced/unvoiced decisions
	:param time_stepF0: time step to compute the pitch, default value is 0 and Praat will use 0.75 / minf0
	:param minf0: minimum frequency for the pitch in Hz, default is 75Hz
	:param maxf0: maximum frequency for the pitch in Hz, default is 600
	:param maxVUVPeriod: maximum interval that considered part of a larger voiced interval, default 0.02
	:param averageVUVPeriod: half of this value will be taken to be the amount to which a voiced interval will extend 							beyond its initial and final points, default is 0.01
	:returns: nothing
	"""
	# Load sound with Parselmouth
	sound = parselmouth.Sound(audio_filaname)

	# Create pitch object
	pitch = call(sound, "To Pitch", time_stepF0, minf0, maxf0)

	# Create pitch tier and save to file
	pitch_tier = call(pitch, "Down to PitchTier")
	call(pitch_tier, "Write to headerless spreadsheet file", resultsp)

	# Create point process and textgrid for voicing decisions
	point_process = call(pitch, "To PointProcess")
	textgrid = call(point_process, "To TextGrid (vuv)", maxVUVPeriod, averageVUVPeriod)
	call(textgrid, "Write to short text file", resultst)

def praat_formants(audio_filename, results_filename,sizeframe,step, n_formants=5, max_formant=5500):
	"""
	Uses Parselmouth to obtain the formants for a wav file.
	It writes the results into a text file.
	These results can then be read using the function decodeFormants.

	:param audio_filaname: Full path to the wav file, string
	:param results_filename: Full path to the resulting file with the formants
	:param sizeframe: window size
	:param step: time step to compute formants
	:param n_formants: number of formants to look for
	:param max_formant: maximum frequencyof formants to look for
	:returns: nothing
	"""
	# Load sound with Parselmouth
	sound = parselmouth.Sound(audio_filename)

	# Create formant object using Burg method
	# Parameters: time_step, max_num_formants, max_formant, window_length, pre_emphasis
	formant = call(sound, "To Formant (burg)", step, n_formants, max_formant, float(sizeframe)/2, 50)

	# Save formant object to file
	call(formant, "Write to short text file", results_filename)

def read_textgrid_trans(file_textgrid, data_audio, fs, win_trans=0.04):
	"""
	This function reads a text file with the text grid with voiced/unvoiced
	decisions then finds the onsets (unvoiced -> voiced) and
	offsets (voiced -> unvoiced) and then reads the audio data to returns
	lists of segments of lenght win_trans around these transitions.

	:param file_textgrid: The text file with the text grid with voicing decisions.
	:param data_audio: the audio signal.
	:param fs: sampling frequency of the audio signal.
	:param win_trans: the transition window lenght, default 0.04
	:returns segments: List with both onset and offset transition segments.
	:returns segments_onset: List with onset transition segments
	:returns segments_offset: List with offset transition segments
	"""
	segments=[]
	segments_onset=[]
	segments_offset=[]
	prev_trans=""
	prev_line=0
	with open(file_textgrid) as fp:
		for line in fp:
			line = line.strip('\n')
			if line in ('"V"', '"U"'):
				transVal=int(float(prev_line)*fs)-1
				segment=data_audio[int(transVal-win_trans*fs):int(transVal+win_trans*fs)]
				segments.append(segment)
				if prev_trans in ('"V"', ""):
					segments_onset.append(segment)
				elif prev_trans=='"U"':
					segments_offset.append(segment)
				prev_trans=line
			prev_line=line
	return segments,segments_onset,segments_offset

def decodeF0(fileTxt,len_signal=0, time_stepF0=0):
	"""
	Reads the content of a pitch file created with praat_vuv function.
	By default it will return the contents of the file in two arrays,
	one for the actual values of pitch and the other with the time stamps.
	Optionally the lenght of the signal and the time step of the pitch
	values can be provided to return an array with the full pitch contour
	for the signal, with padded zeros for unvoiced segments.

	:param fileTxt: File with the pitch, which can be generated using the function praat_vuv
	:param len_signal: Lenght of the audio signal in
	:param time_stepF0: The time step of pitch values. Optional.
	:returns pitch: Numpy array with the values of the pitch.
	:returns time_voiced: time stamp for each pitch value.
	"""
	if os.stat(fileTxt).st_size==0:
		return np.array([0]), np.array([0])
	pitch_data=np.loadtxt(fileTxt)
	if len(pitch_data.shape)>1:
		time_voiced=pitch_data[:,0] # First column is the time stamp vector
		pitch=pitch_data[:,1] # Second column
	elif len(pitch_data.shape)==1: # Only one point of data
		time_voiced=pitch_data[0] # First datum is the time stamp
		pitch=pitch_data[1] # Second datum is the pitch value
	if len_signal>0:
		n_frames=int(len_signal/time_stepF0)
		t=np.linspace(0.0,len_signal,n_frames)
		pitch_zeros=np.zeros(int(n_frames))
		if len(pitch_data.shape)>1:
			for idx,time_p in enumerate(time_voiced):
				argmin=np.argmin(np.abs(t-time_p))
				pitch_zeros[argmin]=pitch[idx]
		else:
			argmin=np.argmin(np.abs(t-time_voiced))
			pitch_zeros[argmin]=pitch
		return pitch_zeros, t
	return pitch, time_voiced

def decodeFormants(fileTxt):
	"""
	Read the praat textgrid file for formants and return the array

	:param fileTxt: File with the formants, which can be generated using the '''praat_formants'''
	:returns F1: Numpy array containing the values for the first formant
	:returns F2: Numpy array containing the values for the second formant
	"""
	with open(fileTxt, 'r') as fid:
		datam=fid.read()
	fid.close()
	end_line1=multi_find(datam, '\n')
	F1=[]
	F2=[]
	ji=10
	while (ji<len(end_line1)-1):
		line1=datam[end_line1[ji]+1:end_line1[ji+1]]
		cond=(line1 in ('3', '4', '5'))
		if (cond):
			F1.append(float(datam[end_line1[ji+1]+1:end_line1[ji+2]]))
			F2.append(float(datam[end_line1[ji+3]+1:end_line1[ji+4]]))
		ji=ji+1
	F1=np.asarray(F1)
	F2=np.asarray(F2)
	return F1, F2


# ============================================================================
# IN-MEMORY FUNCTIONS (New efficient API using Parselmouth directly)
# ============================================================================

def extract_pitch_and_voicing(audio_filename, time_stepF0=0, minf0=75, maxf0=600, maxVUVPeriod=0.02, averageVUVPeriod=0.01, len_signal=0):
	"""
	Extract pitch (F0) and voicing information directly in memory using Parselmouth.
	More efficient than praat_vuv + decodeF0 as it avoids file I/O.

	:param audio_filename: Full path to the wav file or Parselmouth Sound object
	:param time_stepF0: time step to compute the pitch, default value is 0 and Praat will use 0.75 / minf0
	:param minf0: minimum frequency for the pitch in Hz, default is 75Hz
	:param maxf0: maximum frequency for the pitch in Hz, default is 600
	:param maxVUVPeriod: maximum interval that considered part of a larger voiced interval, default 0.02
	:param averageVUVPeriod: half of this value will be taken to be the amount to which a voiced interval will extend beyond its initial and final points, default is 0.01
	:param len_signal: length of the audio signal (in seconds). If provided, returns full pitch contour with zeros for unvoiced segments
	:returns pitch: Numpy array with the values of the pitch
	:returns time_array: Numpy array with time stamps for each pitch value
	:returns textgrid: TextGrid object with voicing decisions (V/U intervals)
	"""
	# Load sound if it's a filename
	if isinstance(audio_filename, str):
		sound = parselmouth.Sound(audio_filename)
	else:
		sound = audio_filename

	# Create pitch object using Parselmouth Python API
	pitch = sound.to_pitch(time_step=time_stepF0 if time_stepF0 > 0 else None,
	                       pitch_floor=minf0,
	                       pitch_ceiling=maxf0)

	# Extract pitch values and times
	pitch_values = []
	time_values = []

	for i in range(pitch.n_frames):
		t = pitch.t1 + i * pitch.time_step
		f0 = pitch.get_value_at_time(t)
		if not np.isnan(f0) and f0 > 0:
			pitch_values.append(f0)
			time_values.append(t)

	pitch_array = np.array(pitch_values)
	time_array = np.array(time_values)

	# Create textgrid for voicing decisions
	pitch_praat = call(sound, "To Pitch", time_stepF0, minf0, maxf0)
	point_process = call(pitch_praat, "To PointProcess")
	textgrid = call(point_process, "To TextGrid (vuv)", maxVUVPeriod, averageVUVPeriod)

	# If len_signal is provided, create full contour with zeros for unvoiced
	if len_signal > 0 and time_stepF0 > 0:
		n_frames = int(len_signal / time_stepF0)
		t = np.linspace(0.0, len_signal, n_frames)
		pitch_zeros = np.zeros(int(n_frames))

		if len(pitch_array) > 0:
			for idx, time_p in enumerate(time_array):
				argmin = np.argmin(np.abs(t - time_p))
				pitch_zeros[argmin] = pitch_array[idx]

		return pitch_zeros, t, textgrid

	return pitch_array, time_array, textgrid


def extract_formants(audio_filename, sizeframe, step, n_formants=5, max_formant=5500):
	"""
	Extract formant frequencies directly in memory using Parselmouth.
	More efficient than praat_formants + decodeFormants as it avoids file I/O.

	:param audio_filename: Full path to the wav file or Parselmouth Sound object
	:param sizeframe: window size for formant analysis
	:param step: time step to compute formants
	:param n_formants: number of formants to look for (default 5)
	:param max_formant: maximum frequency of formants to look for (default 5500)
	:returns F1: Numpy array containing the values for the first formant
	:returns F2: Numpy array containing the values for the second formant
	:returns F3: Numpy array containing the values for the third formant (optional)
	:returns F4: Numpy array containing the values for the fourth formant (optional)
	:returns times: Numpy array with time stamps for each formant frame
	"""
	# Load sound if it's a filename
	if isinstance(audio_filename, str):
		sound = parselmouth.Sound(audio_filename)
	else:
		sound = audio_filename

	# Create formant object using Parselmouth Python API
	formant = sound.to_formant_burg(time_step=step,
	                                max_number_of_formants=n_formants,
	                                maximum_formant=max_formant,
	                                window_length=float(sizeframe)/2,
	                                pre_emphasis_from=50)

	# Extract formant values
	F1_values = []
	F2_values = []
	F3_values = []
	F4_values = []
	times = []

	for i in range(formant.n_frames):
		t = formant.t1 + i * formant.time_step

		# Get formant values (returns NaN if undefined)
		f1 = formant.get_value_at_time(formant_number=1, time=t)
		f2 = formant.get_value_at_time(formant_number=2, time=t)
		f3 = formant.get_value_at_time(formant_number=3, time=t) if n_formants >= 3 else np.nan
		f4 = formant.get_value_at_time(formant_number=4, time=t) if n_formants >= 4 else np.nan

		# Only include frames where F1 and F2 are defined
		if not (np.isnan(f1) or np.isnan(f2)):
			F1_values.append(f1)
			F2_values.append(f2)
			F3_values.append(f3 if not np.isnan(f3) else 0)
			F4_values.append(f4 if not np.isnan(f4) else 0)
			times.append(t)

	return (np.array(F1_values), np.array(F2_values),
	        np.array(F3_values), np.array(F4_values), np.array(times))


def extract_voicing_segments(textgrid, data_audio, fs, win_trans=0.04):
	"""
	Extract voiced/unvoiced transition segments from a TextGrid object.
	This is the in-memory version of read_textgrid_trans.

	:param textgrid: Parselmouth TextGrid object with voicing decisions
	:param data_audio: the audio signal (numpy array)
	:param fs: sampling frequency of the audio signal
	:param win_trans: the transition window length in seconds, default 0.04
	:returns segments: List with both onset and offset transition segments
	:returns segments_onset: List with onset transition segments (U->V)
	:returns segments_offset: List with offset transition segments (V->U)
	"""
	segments = []
	segments_onset = []
	segments_offset = []

	# Get number of intervals in the first tier
	n_intervals = call(textgrid, "Get number of intervals", 1)

	prev_label = ""
	for i in range(1, n_intervals + 1):
		label = call(textgrid, "Get label of interval", 1, i)
		start_time = call(textgrid, "Get start time of interval", 1, i)

		# Process transitions
		if i > 1:  # Skip first interval as there's no previous
			transVal = int(start_time * fs) - 1

			# Extract segment around transition
			start_idx = int(transVal - win_trans * fs)
			end_idx = int(transVal + win_trans * fs)

			# Ensure indices are within bounds
			start_idx = max(0, start_idx)
			end_idx = min(len(data_audio), end_idx)

			segment = data_audio[start_idx:end_idx]
			segments.append(segment)

			# Classify as onset or offset
			if prev_label == "V" or prev_label == "" or prev_label == '"V"':
				segments_onset.append(segment)
			elif prev_label == "U" or prev_label == '"U"':
				segments_offset.append(segment)

		prev_label = label

	return segments, segments_onset, segments_offset
