// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_file_ext
CharacterVector fast_file_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_native
LogicalVector fast_is_native(CharacterVector extensions, CharacterVector nativeFormats);
RcppExport SEXP _superassp_fast_is_native(SEXP extensionsSEXP, SEXP nativeFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_native(extensions, nativeFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_lossless
LogicalVector fast_is_lossless(CharacterVector extensions, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_is_lossless(SEXP extensionsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_lossless(extensions, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_strip_file_protocol
CharacterVector fast_strip_file_protocol(CharacterVector paths);
RcppExport SEXP _superassp_fast_strip_file_protocol(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_strip_file_protocol(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_recycle_times
NumericVector fast_recycle_times(NumericVector times, int n);
RcppExport SEXP _superassp_fast_recycle_times(SEXP timesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_recycle_times(times, n));
    return rcpp_result_gen;
END_RCPP
}
// fast_validate_times
bool fast_validate_times(NumericVector beginTimes, NumericVector endTimes, CharacterVector filenames);
RcppExport SEXP _superassp_fast_validate_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP filenamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filenames(filenamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_validate_times(beginTimes, endTimes, filenames));
    return rcpp_result_gen;
END_RCPP
}
// fast_rename_tracks
List fast_rename_tracks(List objList, CharacterVector newNames);
RcppExport SEXP _superassp_fast_rename_tracks(SEXP objListSEXP, SEXP newNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objList(objListSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type newNames(newNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rename_tracks(objList, newNames));
    return rcpp_result_gen;
END_RCPP
}
// fast_generate_output_paths
CharacterVector fast_generate_output_paths(CharacterVector inputPaths, std::string outputExt, LogicalVector isNative, LogicalVector convertTimewindow);
RcppExport SEXP _superassp_fast_generate_output_paths(SEXP inputPathsSEXP, SEXP outputExtSEXP, SEXP isNativeSEXP, SEXP convertTimewindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type inputPaths(inputPathsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputExt(outputExtSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type isNative(isNativeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type convertTimewindow(convertTimewindowSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_generate_output_paths(inputPaths, outputExt, isNative, convertTimewindow));
    return rcpp_result_gen;
END_RCPP
}
// fast_calculate_conversion_times
DataFrame fast_calculate_conversion_times(NumericVector beginTimes, NumericVector endTimes, NumericVector durations, double windowShift, IntegerVector indices);
RcppExport SEXP _superassp_fast_calculate_conversion_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP durationsSEXP, SEXP windowShiftSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type durations(durationsSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_calculate_conversion_times(beginTimes, endTimes, durations, windowShift, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_basename
CharacterVector fast_basename(CharacterVector paths);
RcppExport SEXP _superassp_fast_basename(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_basename(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_file_path_sans_ext
CharacterVector fast_file_path_sans_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_path_sans_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_path_sans_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_build_conversion_df
DataFrame fast_build_conversion_df(CharacterVector audioPaths, CharacterVector outputPaths, NumericVector startTimes, NumericVector totalTimes, IntegerVector indices);
RcppExport SEXP _superassp_fast_build_conversion_df(SEXP audioPathsSEXP, SEXP outputPathsSEXP, SEXP startTimesSEXP, SEXP totalTimesSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type audioPaths(audioPathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type outputPaths(outputPathsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startTimes(startTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type totalTimes(totalTimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_build_conversion_df(audioPaths, outputPaths, startTimes, totalTimes, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_check_file_formats
List fast_check_file_formats(CharacterVector paths, CharacterVector nativeFormats, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_check_file_formats(SEXP pathsSEXP, SEXP nativeFormatsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_check_file_formats(paths, nativeFormats, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
