// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crepe_inference_cpp
Rcpp::List crepe_inference_cpp(Rcpp::NumericVector audio, double sample_rate, std::string model_path, int hop_length, int batch_size, bool use_viterbi);
RcppExport SEXP _superassp_crepe_inference_cpp(SEXP audioSEXP, SEXP sample_rateSEXP, SEXP model_pathSEXP, SEXP hop_lengthSEXP, SEXP batch_sizeSEXP, SEXP use_viterbiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type audio(audioSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< std::string >::type model_path(model_pathSEXP);
    Rcpp::traits::input_parameter< int >::type hop_length(hop_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_viterbi(use_viterbiSEXP);
    rcpp_result_gen = Rcpp::wrap(crepe_inference_cpp(audio, sample_rate, model_path, hop_length, batch_size, use_viterbi));
    return rcpp_result_gen;
END_RCPP
}
// fast_file_ext
CharacterVector fast_file_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_native
LogicalVector fast_is_native(CharacterVector extensions, CharacterVector nativeFormats);
RcppExport SEXP _superassp_fast_is_native(SEXP extensionsSEXP, SEXP nativeFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_native(extensions, nativeFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_lossless
LogicalVector fast_is_lossless(CharacterVector extensions, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_is_lossless(SEXP extensionsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_lossless(extensions, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_strip_file_protocol
CharacterVector fast_strip_file_protocol(CharacterVector paths);
RcppExport SEXP _superassp_fast_strip_file_protocol(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_strip_file_protocol(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_recycle_times
NumericVector fast_recycle_times(NumericVector times, int n);
RcppExport SEXP _superassp_fast_recycle_times(SEXP timesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_recycle_times(times, n));
    return rcpp_result_gen;
END_RCPP
}
// fast_validate_times
bool fast_validate_times(NumericVector beginTimes, NumericVector endTimes, CharacterVector filenames);
RcppExport SEXP _superassp_fast_validate_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP filenamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filenames(filenamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_validate_times(beginTimes, endTimes, filenames));
    return rcpp_result_gen;
END_RCPP
}
// fast_rename_tracks
List fast_rename_tracks(List objList, CharacterVector newNames);
RcppExport SEXP _superassp_fast_rename_tracks(SEXP objListSEXP, SEXP newNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objList(objListSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type newNames(newNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rename_tracks(objList, newNames));
    return rcpp_result_gen;
END_RCPP
}
// fast_generate_output_paths
CharacterVector fast_generate_output_paths(CharacterVector inputPaths, std::string outputExt, LogicalVector isNative, LogicalVector convertTimewindow);
RcppExport SEXP _superassp_fast_generate_output_paths(SEXP inputPathsSEXP, SEXP outputExtSEXP, SEXP isNativeSEXP, SEXP convertTimewindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type inputPaths(inputPathsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputExt(outputExtSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type isNative(isNativeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type convertTimewindow(convertTimewindowSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_generate_output_paths(inputPaths, outputExt, isNative, convertTimewindow));
    return rcpp_result_gen;
END_RCPP
}
// fast_calculate_conversion_times
DataFrame fast_calculate_conversion_times(NumericVector beginTimes, NumericVector endTimes, NumericVector durations, double windowShift, IntegerVector indices);
RcppExport SEXP _superassp_fast_calculate_conversion_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP durationsSEXP, SEXP windowShiftSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type durations(durationsSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_calculate_conversion_times(beginTimes, endTimes, durations, windowShift, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_basename
CharacterVector fast_basename(CharacterVector paths);
RcppExport SEXP _superassp_fast_basename(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_basename(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_file_path_sans_ext
CharacterVector fast_file_path_sans_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_path_sans_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_path_sans_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_build_conversion_df
DataFrame fast_build_conversion_df(CharacterVector audioPaths, CharacterVector outputPaths, NumericVector startTimes, NumericVector totalTimes, IntegerVector indices);
RcppExport SEXP _superassp_fast_build_conversion_df(SEXP audioPathsSEXP, SEXP outputPathsSEXP, SEXP startTimesSEXP, SEXP totalTimesSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type audioPaths(audioPathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type outputPaths(outputPathsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startTimes(startTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type totalTimes(totalTimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_build_conversion_df(audioPaths, outputPaths, startTimes, totalTimes, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_check_file_formats
List fast_check_file_formats(CharacterVector paths, CharacterVector nativeFormats, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_check_file_formats(SEXP pathsSEXP, SEXP nativeFormatsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_check_file_formats(paths, nativeFormats, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
// momel_c
Rcpp::DataFrame momel_c(Rcpp::NumericVector f0_values, int window_length, double min_f0, double max_f0, double max_error, int reduced_window_length, double minimal_distance, double minimal_frequency_ratio);
RcppExport SEXP _superassp_momel_c(SEXP f0_valuesSEXP, SEXP window_lengthSEXP, SEXP min_f0SEXP, SEXP max_f0SEXP, SEXP max_errorSEXP, SEXP reduced_window_lengthSEXP, SEXP minimal_distanceSEXP, SEXP minimal_frequency_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type f0_values(f0_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type window_length(window_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type min_f0(min_f0SEXP);
    Rcpp::traits::input_parameter< double >::type max_f0(max_f0SEXP);
    Rcpp::traits::input_parameter< double >::type max_error(max_errorSEXP);
    Rcpp::traits::input_parameter< int >::type reduced_window_length(reduced_window_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type minimal_distance(minimal_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type minimal_frequency_ratio(minimal_frequency_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(momel_c(f0_values, window_length, min_f0, max_f0, max_error, reduced_window_length, minimal_distance, minimal_frequency_ratio));
    return rcpp_result_gen;
END_RCPP
}
// estk_pda_cpp
List estk_pda_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double windowSize, int decimation, int noise_floor, double min_v2uv_coef_thresh, double v2uv_coef_thresh_ratio, double uv2v_coef_thresh, double anti_doubling_thresh, bool peak_tracking, bool verbose);
RcppExport SEXP _superassp_estk_pda_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP decimationSEXP, SEXP noise_floorSEXP, SEXP min_v2uv_coef_threshSEXP, SEXP v2uv_coef_thresh_ratioSEXP, SEXP uv2v_coef_threshSEXP, SEXP anti_doubling_threshSEXP, SEXP peak_trackingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< int >::type decimation(decimationSEXP);
    Rcpp::traits::input_parameter< int >::type noise_floor(noise_floorSEXP);
    Rcpp::traits::input_parameter< double >::type min_v2uv_coef_thresh(min_v2uv_coef_threshSEXP);
    Rcpp::traits::input_parameter< double >::type v2uv_coef_thresh_ratio(v2uv_coef_thresh_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type uv2v_coef_thresh(uv2v_coef_threshSEXP);
    Rcpp::traits::input_parameter< double >::type anti_doubling_thresh(anti_doubling_threshSEXP);
    Rcpp::traits::input_parameter< bool >::type peak_tracking(peak_trackingSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(estk_pda_cpp(audio_obj, minF, maxF, windowShift, windowSize, decimation, noise_floor, min_v2uv_coef_thresh, v2uv_coef_thresh_ratio, uv2v_coef_thresh, anti_doubling_thresh, peak_tracking, verbose));
    return rcpp_result_gen;
END_RCPP
}
// estk_pitchmark_cpp
List estk_pitchmark_cpp(SEXP audio_obj, int lx_low_frequency, int lx_low_order, int lx_high_frequency, int lx_high_order, int df_low_frequency, int df_low_order, int median_order, bool fill, double min_period, double max_period, double def_period, bool invert, bool to_f0, bool verbose);
RcppExport SEXP _superassp_estk_pitchmark_cpp(SEXP audio_objSEXP, SEXP lx_low_frequencySEXP, SEXP lx_low_orderSEXP, SEXP lx_high_frequencySEXP, SEXP lx_high_orderSEXP, SEXP df_low_frequencySEXP, SEXP df_low_orderSEXP, SEXP median_orderSEXP, SEXP fillSEXP, SEXP min_periodSEXP, SEXP max_periodSEXP, SEXP def_periodSEXP, SEXP invertSEXP, SEXP to_f0SEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< int >::type lx_low_frequency(lx_low_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type lx_low_order(lx_low_orderSEXP);
    Rcpp::traits::input_parameter< int >::type lx_high_frequency(lx_high_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type lx_high_order(lx_high_orderSEXP);
    Rcpp::traits::input_parameter< int >::type df_low_frequency(df_low_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type df_low_order(df_low_orderSEXP);
    Rcpp::traits::input_parameter< int >::type median_order(median_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type fill(fillSEXP);
    Rcpp::traits::input_parameter< double >::type min_period(min_periodSEXP);
    Rcpp::traits::input_parameter< double >::type max_period(max_periodSEXP);
    Rcpp::traits::input_parameter< double >::type def_period(def_periodSEXP);
    Rcpp::traits::input_parameter< bool >::type invert(invertSEXP);
    Rcpp::traits::input_parameter< bool >::type to_f0(to_f0SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(estk_pitchmark_cpp(audio_obj, lx_low_frequency, lx_low_order, lx_high_frequency, lx_high_order, df_low_frequency, df_low_order, median_order, fill, min_period, max_period, def_period, invert, to_f0, verbose));
    return rcpp_result_gen;
END_RCPP
}
// gfmiaif_cpp
Rcpp::List gfmiaif_cpp(Rcpp::NumericVector audio, int sample_rate, double window_shift_sec, double window_size_sec, int nv, int ng, double d, std::string window_type);
RcppExport SEXP _superassp_gfmiaif_cpp(SEXP audioSEXP, SEXP sample_rateSEXP, SEXP window_shift_secSEXP, SEXP window_size_secSEXP, SEXP nvSEXP, SEXP ngSEXP, SEXP dSEXP, SEXP window_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type audio(audioSEXP);
    Rcpp::traits::input_parameter< int >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type window_shift_sec(window_shift_secSEXP);
    Rcpp::traits::input_parameter< double >::type window_size_sec(window_size_secSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::string >::type window_type(window_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(gfmiaif_cpp(audio, sample_rate, window_shift_sec, window_size_sec, nv, ng, d, window_type));
    return rcpp_result_gen;
END_RCPP
}
// iaif_cpp
Rcpp::List iaif_cpp(Rcpp::NumericVector x_in, double fs, int p_vt, int p_gl, double d, bool hpfilt);
RcppExport SEXP _superassp_iaif_cpp(SEXP x_inSEXP, SEXP fsSEXP, SEXP p_vtSEXP, SEXP p_glSEXP, SEXP dSEXP, SEXP hpfiltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< int >::type p_vt(p_vtSEXP);
    Rcpp::traits::input_parameter< int >::type p_gl(p_glSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type hpfilt(hpfiltSEXP);
    rcpp_result_gen = Rcpp::wrap(iaif_cpp(x_in, fs, p_vt, p_gl, d, hpfilt));
    return rcpp_result_gen;
END_RCPP
}
// extract_vq_params_cpp
Rcpp::List extract_vq_params_cpp(Rcpp::NumericVector glottal_flow, Rcpp::NumericVector glottal_derivative, double fs, double f0, Rcpp::Nullable<Rcpp::IntegerVector> gci);
RcppExport SEXP _superassp_extract_vq_params_cpp(SEXP glottal_flowSEXP, SEXP glottal_derivativeSEXP, SEXP fsSEXP, SEXP f0SEXP, SEXP gciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type glottal_flow(glottal_flowSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type glottal_derivative(glottal_derivativeSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< double >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type gci(gciSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_vq_params_cpp(glottal_flow, glottal_derivative, fs, f0, gci));
    return rcpp_result_gen;
END_RCPP
}
// opensmile_extract_cpp
List opensmile_extract_cpp(SEXP audio_obj, std::string config_file, std::string feature_set_name, bool verbose);
RcppExport SEXP _superassp_opensmile_extract_cpp(SEXP audio_objSEXP, SEXP config_fileSEXP, SEXP feature_set_nameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< std::string >::type config_file(config_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type feature_set_name(feature_set_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(opensmile_extract_cpp(audio_obj, config_file, feature_set_name, verbose));
    return rcpp_result_gen;
END_RCPP
}
// opensmile_gemaps_cpp
List opensmile_gemaps_cpp(SEXP audio_obj, std::string config_file, bool verbose);
RcppExport SEXP _superassp_opensmile_gemaps_cpp(SEXP audio_objSEXP, SEXP config_fileSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< std::string >::type config_file(config_fileSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(opensmile_gemaps_cpp(audio_obj, config_file, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ort_available_cpp
bool ort_available_cpp();
RcppExport SEXP _superassp_ort_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ort_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// ort_version_cpp
std::string ort_version_cpp();
RcppExport SEXP _superassp_ort_version_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ort_version_cpp());
    return rcpp_result_gen;
END_RCPP
}
// ort_lib_path_cpp
std::string ort_lib_path_cpp();
RcppExport SEXP _superassp_ort_lib_path_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ort_lib_path_cpp());
    return rcpp_result_gen;
END_RCPP
}
// ort_set_lib_dir_cpp
void ort_set_lib_dir_cpp(std::string dir);
RcppExport SEXP _superassp_ort_set_lib_dir_cpp(SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    ort_set_lib_dir_cpp(dir);
    return R_NilValue;
END_RCPP
}
// ort_cleanup_cpp
void ort_cleanup_cpp();
RcppExport SEXP _superassp_ort_cleanup_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    ort_cleanup_cpp();
    return R_NilValue;
END_RCPP
}
// ort_create_session_cpp
SEXP ort_create_session_cpp(std::string model_path, int num_threads);
RcppExport SEXP _superassp_ort_create_session_cpp(SEXP model_pathSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model_path(model_pathSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ort_create_session_cpp(model_path, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// ort_run_cpp
Rcpp::List ort_run_cpp(SEXP session_xptr, std::vector<std::string> input_names, Rcpp::List input_data_list, Rcpp::List input_shapes_list, Rcpp::Nullable<std::vector<std::string> > output_names);
RcppExport SEXP _superassp_ort_run_cpp(SEXP session_xptrSEXP, SEXP input_namesSEXP, SEXP input_data_listSEXP, SEXP input_shapes_listSEXP, SEXP output_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session_xptr(session_xptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input_names(input_namesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type input_data_list(input_data_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type input_shapes_list(input_shapes_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<std::string> > >::type output_names(output_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ort_run_cpp(session_xptr, input_names, input_data_list, input_shapes_list, output_names));
    return rcpp_result_gen;
END_RCPP
}
// ort_session_input_info_cpp
Rcpp::List ort_session_input_info_cpp(SEXP session_xptr);
RcppExport SEXP _superassp_ort_session_input_info_cpp(SEXP session_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session_xptr(session_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ort_session_input_info_cpp(session_xptr));
    return rcpp_result_gen;
END_RCPP
}
// ort_session_output_info_cpp
Rcpp::List ort_session_output_info_cpp(SEXP session_xptr);
RcppExport SEXP _superassp_ort_session_output_info_cpp(SEXP session_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session_xptr(session_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ort_session_output_info_cpp(session_xptr));
    return rcpp_result_gen;
END_RCPP
}
// snackf_cpp
List snackf_cpp(SEXP audio_obj, int numFormants, int lpcOrder, double windowLength, double windowShift, double preEmphasis, double dsFreq, double nomF1, int lpcType, int windowType, bool verbose);
RcppExport SEXP _superassp_snackf_cpp(SEXP audio_objSEXP, SEXP numFormantsSEXP, SEXP lpcOrderSEXP, SEXP windowLengthSEXP, SEXP windowShiftSEXP, SEXP preEmphasisSEXP, SEXP dsFreqSEXP, SEXP nomF1SEXP, SEXP lpcTypeSEXP, SEXP windowTypeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< int >::type numFormants(numFormantsSEXP);
    Rcpp::traits::input_parameter< int >::type lpcOrder(lpcOrderSEXP);
    Rcpp::traits::input_parameter< double >::type windowLength(windowLengthSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type preEmphasis(preEmphasisSEXP);
    Rcpp::traits::input_parameter< double >::type dsFreq(dsFreqSEXP);
    Rcpp::traits::input_parameter< double >::type nomF1(nomF1SEXP);
    Rcpp::traits::input_parameter< int >::type lpcType(lpcTypeSEXP);
    Rcpp::traits::input_parameter< int >::type windowType(windowTypeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(snackf_cpp(audio_obj, numFormants, lpcOrder, windowLength, windowShift, preEmphasis, dsFreq, nomF1, lpcType, windowType, verbose));
    return rcpp_result_gen;
END_RCPP
}
// snackp_cpp
List snackp_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voiceBias, bool verbose);
RcppExport SEXP _superassp_snackp_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voiceBiasSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voiceBias(voiceBiasSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(snackp_cpp(audio_obj, minF, maxF, windowShift, voiceBias, verbose));
    return rcpp_result_gen;
END_RCPP
}
// d4c_cpp
List d4c_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, double threshold, bool verbose);
RcppExport SEXP _superassp_d4c_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(d4c_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sptk_mfcc_cpp
List sptk_mfcc_cpp(SEXP audio_obj, int n_mfcc, int n_mels, double windowShift, double windowSize, double fmin, double fmax, int lifter, double floor, bool verbose);
RcppExport SEXP _superassp_sptk_mfcc_cpp(SEXP audio_objSEXP, SEXP n_mfccSEXP, SEXP n_melsSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP fminSEXP, SEXP fmaxSEXP, SEXP lifterSEXP, SEXP floorSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< int >::type n_mfcc(n_mfccSEXP);
    Rcpp::traits::input_parameter< int >::type n_mels(n_melsSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< double >::type fmin(fminSEXP);
    Rcpp::traits::input_parameter< double >::type fmax(fmaxSEXP);
    Rcpp::traits::input_parameter< int >::type lifter(lifterSEXP);
    Rcpp::traits::input_parameter< double >::type floor(floorSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sptk_mfcc_cpp(audio_obj, n_mfcc, n_mels, windowShift, windowSize, fmin, fmax, lifter, floor, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rapt_cpp
List rapt_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_rapt_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rapt_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// swipe_cpp
List swipe_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_swipe_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(swipe_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// reaper_cpp
List reaper_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_reaper_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(reaper_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dio_cpp
List dio_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_dio_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dio_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// harvest_cpp
List harvest_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_harvest_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(harvest_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// resample_polyphase_cpp
Rcpp::NumericVector resample_polyphase_cpp(const Rcpp::NumericVector& x, const Rcpp::NumericVector& h, const int up, const int down, const int n_out, const int trim);
RcppExport SEXP _superassp_resample_polyphase_cpp(SEXP xSEXP, SEXP hSEXP, SEXP upSEXP, SEXP downSEXP, SEXP n_outSEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type up(upSEXP);
    Rcpp::traits::input_parameter< const int >::type down(downSEXP);
    Rcpp::traits::input_parameter< const int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< const int >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_polyphase_cpp(x, h, up, down, n_out, trim));
    return rcpp_result_gen;
END_RCPP
}
// srh_core_cpp
Rcpp::List srh_core_cpp(const Rcpp::NumericVector& sig, const int fs, const Rcpp::IntegerVector& edge, const int n_candidate);
RcppExport SEXP _superassp_srh_core_cpp(SEXP sigSEXP, SEXP fsSEXP, SEXP edgeSEXP, SEXP n_candidateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< const int >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_candidate(n_candidateSEXP);
    rcpp_result_gen = Rcpp::wrap(srh_core_cpp(sig, fs, edge, n_candidate));
    return rcpp_result_gen;
END_RCPP
}
// srh_variant_cpp
Rcpp::List srh_variant_cpp(const Rcpp::NumericVector& wave, const int fs, const Rcpp::IntegerVector& edge);
RcppExport SEXP _superassp_srh_variant_cpp(SEXP waveSEXP, SEXP fsSEXP, SEXP edgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< const int >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type edge(edgeSEXP);
    rcpp_result_gen = Rcpp::wrap(srh_variant_cpp(wave, fs, edge));
    return rcpp_result_gen;
END_RCPP
}
// srh_variant_debug_cpp
Rcpp::List srh_variant_debug_cpp(const Rcpp::NumericVector& wave, const int fs, const Rcpp::IntegerVector& edge);
RcppExport SEXP _superassp_srh_variant_debug_cpp(SEXP waveSEXP, SEXP fsSEXP, SEXP edgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< const int >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type edge(edgeSEXP);
    rcpp_result_gen = Rcpp::wrap(srh_variant_debug_cpp(wave, fs, edge));
    return rcpp_result_gen;
END_RCPP
}
// tandem_pitch_cpp
Rcpp::List tandem_pitch_cpp(Rcpp::NumericVector audio_signal, int sample_rate, double min_pitch, double max_pitch, std::string net_path);
RcppExport SEXP _superassp_tandem_pitch_cpp(SEXP audio_signalSEXP, SEXP sample_rateSEXP, SEXP min_pitchSEXP, SEXP max_pitchSEXP, SEXP net_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type audio_signal(audio_signalSEXP);
    Rcpp::traits::input_parameter< int >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type min_pitch(min_pitchSEXP);
    Rcpp::traits::input_parameter< double >::type max_pitch(max_pitchSEXP);
    Rcpp::traits::input_parameter< std::string >::type net_path(net_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(tandem_pitch_cpp(audio_signal, sample_rate, min_pitch, max_pitch, net_path));
    return rcpp_result_gen;
END_RCPP
}
// pre_emphasis_cpp
arma::mat pre_emphasis_cpp(const arma::vec& x, const double preemp);
RcppExport SEXP _superassp_pre_emphasis_cpp(SEXP xSEXP, SEXP preempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type preemp(preempSEXP);
    rcpp_result_gen = Rcpp::wrap(pre_emphasis_cpp(x, preemp));
    return rcpp_result_gen;
END_RCPP
}
// tvlp_l2_cpp
arma::mat tvlp_l2_cpp(const arma::vec& x, const int p, const int q);
RcppExport SEXP _superassp_tvlp_l2_cpp(SEXP xSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(tvlp_l2_cpp(x, p, q));
    return rcpp_result_gen;
END_RCPP
}
// tvwlp_l2_cpp
arma::mat tvwlp_l2_cpp(const arma::vec& x, const int p, const int q, const arma::vec& w);
RcppExport SEXP _superassp_tvwlp_l2_cpp(SEXP xSEXP, SEXP pSEXP, SEXP qSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(tvwlp_l2_cpp(x, p, q, w));
    return rcpp_result_gen;
END_RCPP
}
// tvlptoformants_akitofi_cpp
List tvlptoformants_akitofi_cpp(const arma::mat& aki, const int nx, const int npeaks, const double fs);
RcppExport SEXP _superassp_tvlptoformants_akitofi_cpp(SEXP akiSEXP, SEXP nxSEXP, SEXP npeaksSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type aki(akiSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const int >::type npeaks(npeaksSEXP);
    Rcpp::traits::input_parameter< const double >::type fs(fsSEXP);
    rcpp_result_gen = Rcpp::wrap(tvlptoformants_akitofi_cpp(aki, nx, npeaks, fs));
    return rcpp_result_gen;
END_RCPP
}
// get_lpc_residual_cpp
arma::vec get_lpc_residual_cpp(const arma::vec& wave, const int l, const int shift, const int order);
RcppExport SEXP _superassp_get_lpc_residual_cpp(SEXP waveSEXP, SEXP lSEXP, SEXP shiftSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< const int >::type l(lSEXP);
    Rcpp::traits::input_parameter< const int >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< const int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(get_lpc_residual_cpp(wave, l, shift, order));
    return rcpp_result_gen;
END_RCPP
}
// vat_ann_forward_cpp
NumericVector vat_ann_forward_cpp(NumericMatrix X_r, NumericMatrix IW_r, NumericVector b_h_r, NumericMatrix LW_r, NumericVector b_o_r, NumericVector mini_r, NumericVector maxi_r, std::string out_act);
RcppExport SEXP _superassp_vat_ann_forward_cpp(SEXP X_rSEXP, SEXP IW_rSEXP, SEXP b_h_rSEXP, SEXP LW_rSEXP, SEXP b_o_rSEXP, SEXP mini_rSEXP, SEXP maxi_rSEXP, SEXP out_actSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X_r(X_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type IW_r(IW_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_h_r(b_h_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type LW_r(LW_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_o_r(b_o_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mini_r(mini_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxi_r(maxi_rSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_act(out_actSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_ann_forward_cpp(X_r, IW_r, b_h_r, LW_r, b_o_r, mini_r, maxi_r, out_act));
    return rcpp_result_gen;
END_RCPP
}
// vat_creak_features_cpp
NumericMatrix vat_creak_features_cpp(NumericVector x_r, double fs);
RcppExport SEXP _superassp_vat_creak_features_cpp(SEXP x_rSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_creak_features_cpp(x_r, fs));
    return rcpp_result_gen;
END_RCPP
}
// vat_creak_detect_cpp
List vat_creak_detect_cpp(NumericVector x_r, double fs, NumericMatrix IW, NumericVector b_h, NumericMatrix LW, NumericVector b_o, NumericVector mini, NumericVector maxi, double threshold);
RcppExport SEXP _superassp_vat_creak_detect_cpp(SEXP x_rSEXP, SEXP fsSEXP, SEXP IWSEXP, SEXP b_hSEXP, SEXP LWSEXP, SEXP b_oSEXP, SEXP miniSEXP, SEXP maxiSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type IW(IWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_h(b_hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type LW(LWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_o(b_oSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mini(miniSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxi(maxiSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_creak_detect_cpp(x_r, fs, IW, b_h, LW, b_o, mini, maxi, threshold));
    return rcpp_result_gen;
END_RCPP
}
// vat_hamming_cpp
NumericVector vat_hamming_cpp(int N, bool symmetric);
RcppExport SEXP _superassp_vat_hamming_cpp(SEXP NSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_hamming_cpp(N, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// vat_hanning_cpp
NumericVector vat_hanning_cpp(int N, bool symmetric);
RcppExport SEXP _superassp_vat_hanning_cpp(SEXP NSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_hanning_cpp(N, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// vat_kaiser_cpp
NumericVector vat_kaiser_cpp(int N, double beta);
RcppExport SEXP _superassp_vat_kaiser_cpp(SEXP NSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_kaiser_cpp(N, beta));
    return rcpp_result_gen;
END_RCPP
}
// vat_filter_cpp
NumericVector vat_filter_cpp(NumericVector b, NumericVector a, NumericVector x, Nullable<NumericVector> zi);
RcppExport SEXP _superassp_vat_filter_cpp(SEXP bSEXP, SEXP aSEXP, SEXP xSEXP, SEXP ziSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type zi(ziSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_filter_cpp(b, a, x, zi));
    return rcpp_result_gen;
END_RCPP
}
// vat_filtfilt_cpp
NumericVector vat_filtfilt_cpp(NumericVector b, NumericVector a, NumericVector x);
RcppExport SEXP _superassp_vat_filtfilt_cpp(SEXP bSEXP, SEXP aSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_filtfilt_cpp(b, a, x));
    return rcpp_result_gen;
END_RCPP
}
// vat_fir1_cpp
NumericVector vat_fir1_cpp(int n, NumericVector Wn, std::string type);
RcppExport SEXP _superassp_vat_fir1_cpp(SEXP nSEXP, SEXP WnSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wn(WnSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_fir1_cpp(n, Wn, type));
    return rcpp_result_gen;
END_RCPP
}
// vat_butter_cpp
List vat_butter_cpp(int n, NumericVector Wn, std::string type);
RcppExport SEXP _superassp_vat_butter_cpp(SEXP nSEXP, SEXP WnSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wn(WnSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_butter_cpp(n, Wn, type));
    return rcpp_result_gen;
END_RCPP
}
// vat_medfilt1_cpp
NumericVector vat_medfilt1_cpp(NumericVector x, int n);
RcppExport SEXP _superassp_vat_medfilt1_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_medfilt1_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}
// vat_interp1_linear_cpp
NumericVector vat_interp1_linear_cpp(NumericVector x, NumericVector y, NumericVector xq);
RcppExport SEXP _superassp_vat_interp1_linear_cpp(SEXP xSEXP, SEXP ySEXP, SEXP xqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xq(xqSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_interp1_linear_cpp(x, y, xq));
    return rcpp_result_gen;
END_RCPP
}
// vat_interp1_spline_cpp
NumericVector vat_interp1_spline_cpp(NumericVector x, NumericVector y, NumericVector xq);
RcppExport SEXP _superassp_vat_interp1_spline_cpp(SEXP xSEXP, SEXP ySEXP, SEXP xqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xq(xqSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_interp1_spline_cpp(x, y, xq));
    return rcpp_result_gen;
END_RCPP
}
// vat_findpeaks_cpp
List vat_findpeaks_cpp(NumericVector x, double min_peak_height, int min_peak_distance);
RcppExport SEXP _superassp_vat_findpeaks_cpp(SEXP xSEXP, SEXP min_peak_heightSEXP, SEXP min_peak_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type min_peak_height(min_peak_heightSEXP);
    Rcpp::traits::input_parameter< int >::type min_peak_distance(min_peak_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_findpeaks_cpp(x, min_peak_height, min_peak_distance));
    return rcpp_result_gen;
END_RCPP
}
// vat_resample_cpp
NumericVector vat_resample_cpp(NumericVector x, int p, int q, double beta);
RcppExport SEXP _superassp_vat_resample_cpp(SEXP xSEXP, SEXP pSEXP, SEXP qSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_resample_cpp(x, p, q, beta));
    return rcpp_result_gen;
END_RCPP
}
// vat_fft_cpp
ComplexVector vat_fft_cpp(NumericVector x, int nfft);
RcppExport SEXP _superassp_vat_fft_cpp(SEXP xSEXP, SEXP nfftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nfft(nfftSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_fft_cpp(x, nfft));
    return rcpp_result_gen;
END_RCPP
}
// vat_lpcauto_cpp
List vat_lpcauto_cpp(NumericVector s, int p);
RcppExport SEXP _superassp_vat_lpcauto_cpp(SEXP sSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lpcauto_cpp(s, p));
    return rcpp_result_gen;
END_RCPP
}
// vat_burg_cpp
List vat_burg_cpp(NumericVector s, int p);
RcppExport SEXP _superassp_vat_burg_cpp(SEXP sSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_burg_cpp(s, p));
    return rcpp_result_gen;
END_RCPP
}
// vat_lpcar2rf_cpp
NumericVector vat_lpcar2rf_cpp(NumericVector ar);
RcppExport SEXP _superassp_vat_lpcar2rf_cpp(SEXP arSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ar(arSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lpcar2rf_cpp(ar));
    return rcpp_result_gen;
END_RCPP
}
// vat_lpcar2ra_cpp
NumericVector vat_lpcar2ra_cpp(NumericVector ar);
RcppExport SEXP _superassp_vat_lpcar2ra_cpp(SEXP arSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ar(arSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lpcar2ra_cpp(ar));
    return rcpp_result_gen;
END_RCPP
}
// vat_lpcrf2rr_cpp
NumericVector vat_lpcrf2rr_cpp(NumericVector k);
RcppExport SEXP _superassp_vat_lpcrf2rr_cpp(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lpcrf2rr_cpp(k));
    return rcpp_result_gen;
END_RCPP
}
// vat_distitar_cpp
double vat_distitar_cpp(NumericVector ar1, NumericVector ar2, bool symmetric);
RcppExport SEXP _superassp_vat_distitar_cpp(SEXP ar1SEXP, SEXP ar2SEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ar1(ar1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ar2(ar2SEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_distitar_cpp(ar1, ar2, symmetric));
    return rcpp_result_gen;
END_RCPP
}
// vat_se_vq_cpp
List vat_se_vq_cpp(NumericVector x_r, double fs, NumericVector f0_r, IntegerVector vuv_r, Nullable<IntegerVector> creak_r, bool var_f0);
RcppExport SEXP _superassp_vat_se_vq_cpp(SEXP x_rSEXP, SEXP fsSEXP, SEXP f0_rSEXP, SEXP vuv_rSEXP, SEXP creak_rSEXP, SEXP var_f0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f0_r(f0_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vuv_r(vuv_rSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type creak_r(creak_rSEXP);
    Rcpp::traits::input_parameter< bool >::type var_f0(var_f0SEXP);
    rcpp_result_gen = Rcpp::wrap(vat_se_vq_cpp(x_r, fs, f0_r, vuv_r, creak_r, var_f0));
    return rcpp_result_gen;
END_RCPP
}
// vat_iaif_full_cpp
List vat_iaif_full_cpp(NumericVector x_r, double fs, IntegerVector gci, int p);
RcppExport SEXP _superassp_vat_iaif_full_cpp(SEXP x_rSEXP, SEXP fsSEXP, SEXP gciSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gci(gciSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_iaif_full_cpp(x_r, fs, gci, p));
    return rcpp_result_gen;
END_RCPP
}
// vat_calc_residual_cpp
List vat_calc_residual_cpp(NumericVector x_r, NumericVector x_lpc_r, int ord_lpc, IntegerVector gci);
RcppExport SEXP _superassp_vat_calc_residual_cpp(SEXP x_rSEXP, SEXP x_lpc_rSEXP, SEXP ord_lpcSEXP, SEXP gciSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_r(x_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_lpc_r(x_lpc_rSEXP);
    Rcpp::traits::input_parameter< int >::type ord_lpc(ord_lpcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gci(gciSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_calc_residual_cpp(x_r, x_lpc_r, ord_lpc, gci));
    return rcpp_result_gen;
END_RCPP
}
// vat_lf_area_newton_cpp
List vat_lf_area_newton_cpp(double Tc, double fs, double Tp, double Te, double Ta, double EE);
RcppExport SEXP _superassp_vat_lf_area_newton_cpp(SEXP TcSEXP, SEXP fsSEXP, SEXP TpSEXP, SEXP TeSEXP, SEXP TaSEXP, SEXP EESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Tc(TcSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< double >::type Tp(TpSEXP);
    Rcpp::traits::input_parameter< double >::type Te(TeSEXP);
    Rcpp::traits::input_parameter< double >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< double >::type EE(EESEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lf_area_newton_cpp(Tc, fs, Tp, Te, Ta, EE));
    return rcpp_result_gen;
END_RCPP
}
// vat_rd2r_cpp
List vat_rd2r_cpp(double Rd, double EE, double F0);
RcppExport SEXP _superassp_vat_rd2r_cpp(SEXP RdSEXP, SEXP EESEXP, SEXP F0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Rd(RdSEXP);
    Rcpp::traits::input_parameter< double >::type EE(EESEXP);
    Rcpp::traits::input_parameter< double >::type F0(F0SEXP);
    rcpp_result_gen = Rcpp::wrap(vat_rd2r_cpp(Rd, EE, F0));
    return rcpp_result_gen;
END_RCPP
}
// vat_lf_cont_cpp
NumericVector vat_lf_cont_cpp(double F0, double fs, double Ra, double Rk, double Rg, double EE);
RcppExport SEXP _superassp_vat_lf_cont_cpp(SEXP F0SEXP, SEXP fsSEXP, SEXP RaSEXP, SEXP RkSEXP, SEXP RgSEXP, SEXP EESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< double >::type Ra(RaSEXP);
    Rcpp::traits::input_parameter< double >::type Rk(RkSEXP);
    Rcpp::traits::input_parameter< double >::type Rg(RgSEXP);
    Rcpp::traits::input_parameter< double >::type EE(EESEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lf_cont_cpp(F0, fs, Ra, Rk, Rg, EE));
    return rcpp_result_gen;
END_RCPP
}
// vat_lpc_residual_cpp
NumericVector vat_lpc_residual_cpp(NumericVector wave_r, int window_len, int shift, int order);
RcppExport SEXP _superassp_vat_lpc_residual_cpp(SEXP wave_rSEXP, SEXP window_lenSEXP, SEXP shiftSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wave_r(wave_rSEXP);
    Rcpp::traits::input_parameter< int >::type window_len(window_lenSEXP);
    Rcpp::traits::input_parameter< int >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_lpc_residual_cpp(wave_r, window_len, shift, order));
    return rcpp_result_gen;
END_RCPP
}
// vat_reson_dynprog_cpp
IntegerVector vat_reson_dynprog_cpp(NumericMatrix gci_rel_amp, IntegerMatrix gci_n, double f0_mean, NumericVector x, double fs, double trans_wgt, double rel_amp_wgt);
RcppExport SEXP _superassp_vat_reson_dynprog_cpp(SEXP gci_rel_ampSEXP, SEXP gci_nSEXP, SEXP f0_meanSEXP, SEXP xSEXP, SEXP fsSEXP, SEXP trans_wgtSEXP, SEXP rel_amp_wgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type gci_rel_amp(gci_rel_ampSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type gci_n(gci_nSEXP);
    Rcpp::traits::input_parameter< double >::type f0_mean(f0_meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< double >::type trans_wgt(trans_wgtSEXP);
    Rcpp::traits::input_parameter< double >::type rel_amp_wgt(rel_amp_wgtSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_reson_dynprog_cpp(gci_rel_amp, gci_n, f0_mean, x, fs, trans_wgt, rel_amp_wgt));
    return rcpp_result_gen;
END_RCPP
}
// vat_srh_pitch_cpp
List vat_srh_pitch_cpp(NumericVector wave_r, double Fs, double F0min, double F0max);
RcppExport SEXP _superassp_vat_srh_pitch_cpp(SEXP wave_rSEXP, SEXP FsSEXP, SEXP F0minSEXP, SEXP F0maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wave_r(wave_rSEXP);
    Rcpp::traits::input_parameter< double >::type Fs(FsSEXP);
    Rcpp::traits::input_parameter< double >::type F0min(F0minSEXP);
    Rcpp::traits::input_parameter< double >::type F0max(F0maxSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_srh_pitch_cpp(wave_r, Fs, F0min, F0max));
    return rcpp_result_gen;
END_RCPP
}
// vat_naq_qoq_h1h2_cpp
List vat_naq_qoq_h1h2_cpp(NumericVector glot_r, double fs, IntegerVector gci_r);
RcppExport SEXP _superassp_vat_naq_qoq_h1h2_cpp(SEXP glot_rSEXP, SEXP fsSEXP, SEXP gci_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type glot_r(glot_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gci_r(gci_rSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_naq_qoq_h1h2_cpp(glot_r, fs, gci_r));
    return rcpp_result_gen;
END_RCPP
}
// vat_daless_decomp_cpp
List vat_daless_decomp_cpp(NumericVector s_r, double fs, IntegerVector i_r);
RcppExport SEXP _superassp_vat_daless_decomp_cpp(SEXP s_rSEXP, SEXP fsSEXP, SEXP i_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s_r(s_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_r(i_rSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_daless_decomp_cpp(s_r, fs, i_r));
    return rcpp_result_gen;
END_RCPP
}
// vat_peakslope_cpp
NumericVector vat_peakslope_cpp(NumericVector s_r, double fs);
RcppExport SEXP _superassp_vat_peakslope_cpp(SEXP s_rSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s_r(s_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_peakslope_cpp(s_r, fs));
    return rcpp_result_gen;
END_RCPP
}
// vat_mdq_cpp
NumericVector vat_mdq_cpp(NumericVector res_r, double fs, IntegerVector gci_r);
RcppExport SEXP _superassp_vat_mdq_cpp(SEXP res_rSEXP, SEXP fsSEXP, SEXP gci_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type res_r(res_rSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gci_r(gci_rSEXP);
    rcpp_result_gen = Rcpp::wrap(vat_mdq_cpp(res_r, fs, gci_r));
    return rcpp_result_gen;
END_RCPP
}
// yin_cpp
List yin_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double windowSize, double threshold, bool verbose);
RcppExport SEXP _superassp_yin_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(yin_cpp(audio_obj, minF, maxF, windowShift, windowSize, threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// pyin_cpp
List pyin_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double windowSize, double threshold, bool verbose);
RcppExport SEXP _superassp_pyin_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(pyin_cpp(audio_obj, minF, maxF, windowShift, windowSize, threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
