// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_file_ext
CharacterVector fast_file_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_native
LogicalVector fast_is_native(CharacterVector extensions, CharacterVector nativeFormats);
RcppExport SEXP _superassp_fast_is_native(SEXP extensionsSEXP, SEXP nativeFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_native(extensions, nativeFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_is_lossless
LogicalVector fast_is_lossless(CharacterVector extensions, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_is_lossless(SEXP extensionsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type extensions(extensionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_is_lossless(extensions, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
// fast_strip_file_protocol
CharacterVector fast_strip_file_protocol(CharacterVector paths);
RcppExport SEXP _superassp_fast_strip_file_protocol(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_strip_file_protocol(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_recycle_times
NumericVector fast_recycle_times(NumericVector times, int n);
RcppExport SEXP _superassp_fast_recycle_times(SEXP timesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_recycle_times(times, n));
    return rcpp_result_gen;
END_RCPP
}
// fast_validate_times
bool fast_validate_times(NumericVector beginTimes, NumericVector endTimes, CharacterVector filenames);
RcppExport SEXP _superassp_fast_validate_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP filenamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filenames(filenamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_validate_times(beginTimes, endTimes, filenames));
    return rcpp_result_gen;
END_RCPP
}
// fast_rename_tracks
List fast_rename_tracks(List objList, CharacterVector newNames);
RcppExport SEXP _superassp_fast_rename_tracks(SEXP objListSEXP, SEXP newNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type objList(objListSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type newNames(newNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rename_tracks(objList, newNames));
    return rcpp_result_gen;
END_RCPP
}
// fast_generate_output_paths
CharacterVector fast_generate_output_paths(CharacterVector inputPaths, std::string outputExt, LogicalVector isNative, LogicalVector convertTimewindow);
RcppExport SEXP _superassp_fast_generate_output_paths(SEXP inputPathsSEXP, SEXP outputExtSEXP, SEXP isNativeSEXP, SEXP convertTimewindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type inputPaths(inputPathsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputExt(outputExtSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type isNative(isNativeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type convertTimewindow(convertTimewindowSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_generate_output_paths(inputPaths, outputExt, isNative, convertTimewindow));
    return rcpp_result_gen;
END_RCPP
}
// fast_calculate_conversion_times
DataFrame fast_calculate_conversion_times(NumericVector beginTimes, NumericVector endTimes, NumericVector durations, double windowShift, IntegerVector indices);
RcppExport SEXP _superassp_fast_calculate_conversion_times(SEXP beginTimesSEXP, SEXP endTimesSEXP, SEXP durationsSEXP, SEXP windowShiftSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beginTimes(beginTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type endTimes(endTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type durations(durationsSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_calculate_conversion_times(beginTimes, endTimes, durations, windowShift, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_basename
CharacterVector fast_basename(CharacterVector paths);
RcppExport SEXP _superassp_fast_basename(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_basename(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_file_path_sans_ext
CharacterVector fast_file_path_sans_ext(CharacterVector paths);
RcppExport SEXP _superassp_fast_file_path_sans_ext(SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_file_path_sans_ext(paths));
    return rcpp_result_gen;
END_RCPP
}
// fast_build_conversion_df
DataFrame fast_build_conversion_df(CharacterVector audioPaths, CharacterVector outputPaths, NumericVector startTimes, NumericVector totalTimes, IntegerVector indices);
RcppExport SEXP _superassp_fast_build_conversion_df(SEXP audioPathsSEXP, SEXP outputPathsSEXP, SEXP startTimesSEXP, SEXP totalTimesSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type audioPaths(audioPathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type outputPaths(outputPathsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startTimes(startTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type totalTimes(totalTimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_build_conversion_df(audioPaths, outputPaths, startTimes, totalTimes, indices));
    return rcpp_result_gen;
END_RCPP
}
// fast_check_file_formats
List fast_check_file_formats(CharacterVector paths, CharacterVector nativeFormats, CharacterVector losslessFormats);
RcppExport SEXP _superassp_fast_check_file_formats(SEXP pathsSEXP, SEXP nativeFormatsSEXP, SEXP losslessFormatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nativeFormats(nativeFormatsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type losslessFormats(losslessFormatsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_check_file_formats(paths, nativeFormats, losslessFormats));
    return rcpp_result_gen;
END_RCPP
}
// estk_pda_cpp
List estk_pda_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double windowSize, int decimation, int noise_floor, double min_v2uv_coef_thresh, double v2uv_coef_thresh_ratio, double uv2v_coef_thresh, double anti_doubling_thresh, bool peak_tracking, bool verbose);
RcppExport SEXP _superassp_estk_pda_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP decimationSEXP, SEXP noise_floorSEXP, SEXP min_v2uv_coef_threshSEXP, SEXP v2uv_coef_thresh_ratioSEXP, SEXP uv2v_coef_threshSEXP, SEXP anti_doubling_threshSEXP, SEXP peak_trackingSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< int >::type decimation(decimationSEXP);
    Rcpp::traits::input_parameter< int >::type noise_floor(noise_floorSEXP);
    Rcpp::traits::input_parameter< double >::type min_v2uv_coef_thresh(min_v2uv_coef_threshSEXP);
    Rcpp::traits::input_parameter< double >::type v2uv_coef_thresh_ratio(v2uv_coef_thresh_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type uv2v_coef_thresh(uv2v_coef_threshSEXP);
    Rcpp::traits::input_parameter< double >::type anti_doubling_thresh(anti_doubling_threshSEXP);
    Rcpp::traits::input_parameter< bool >::type peak_tracking(peak_trackingSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(estk_pda_cpp(audio_obj, minF, maxF, windowShift, windowSize, decimation, noise_floor, min_v2uv_coef_thresh, v2uv_coef_thresh_ratio, uv2v_coef_thresh, anti_doubling_thresh, peak_tracking, verbose));
    return rcpp_result_gen;
END_RCPP
}
// estk_pitchmark_cpp
List estk_pitchmark_cpp(SEXP audio_obj, int lx_low_frequency, int lx_low_order, int lx_high_frequency, int lx_high_order, int df_low_frequency, int df_low_order, int median_order, bool fill, double min_period, double max_period, double def_period, bool invert, bool to_f0, bool verbose);
RcppExport SEXP _superassp_estk_pitchmark_cpp(SEXP audio_objSEXP, SEXP lx_low_frequencySEXP, SEXP lx_low_orderSEXP, SEXP lx_high_frequencySEXP, SEXP lx_high_orderSEXP, SEXP df_low_frequencySEXP, SEXP df_low_orderSEXP, SEXP median_orderSEXP, SEXP fillSEXP, SEXP min_periodSEXP, SEXP max_periodSEXP, SEXP def_periodSEXP, SEXP invertSEXP, SEXP to_f0SEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< int >::type lx_low_frequency(lx_low_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type lx_low_order(lx_low_orderSEXP);
    Rcpp::traits::input_parameter< int >::type lx_high_frequency(lx_high_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type lx_high_order(lx_high_orderSEXP);
    Rcpp::traits::input_parameter< int >::type df_low_frequency(df_low_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type df_low_order(df_low_orderSEXP);
    Rcpp::traits::input_parameter< int >::type median_order(median_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type fill(fillSEXP);
    Rcpp::traits::input_parameter< double >::type min_period(min_periodSEXP);
    Rcpp::traits::input_parameter< double >::type max_period(max_periodSEXP);
    Rcpp::traits::input_parameter< double >::type def_period(def_periodSEXP);
    Rcpp::traits::input_parameter< bool >::type invert(invertSEXP);
    Rcpp::traits::input_parameter< bool >::type to_f0(to_f0SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(estk_pitchmark_cpp(audio_obj, lx_low_frequency, lx_low_order, lx_high_frequency, lx_high_order, df_low_frequency, df_low_order, median_order, fill, min_period, max_period, def_period, invert, to_f0, verbose));
    return rcpp_result_gen;
END_RCPP
}
// opensmile_extract_cpp
List opensmile_extract_cpp(SEXP audio_obj, std::string config_file, std::string feature_set_name, bool verbose);
RcppExport SEXP _superassp_opensmile_extract_cpp(SEXP audio_objSEXP, SEXP config_fileSEXP, SEXP feature_set_nameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< std::string >::type config_file(config_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type feature_set_name(feature_set_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(opensmile_extract_cpp(audio_obj, config_file, feature_set_name, verbose));
    return rcpp_result_gen;
END_RCPP
}
// opensmile_gemaps_cpp
List opensmile_gemaps_cpp(SEXP audio_obj, std::string config_file, bool verbose);
RcppExport SEXP _superassp_opensmile_gemaps_cpp(SEXP audio_objSEXP, SEXP config_fileSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< std::string >::type config_file(config_fileSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(opensmile_gemaps_cpp(audio_obj, config_file, verbose));
    return rcpp_result_gen;
END_RCPP
}
// d4c_cpp
List d4c_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, double threshold, bool verbose);
RcppExport SEXP _superassp_d4c_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(d4c_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sptk_mfcc_cpp
List sptk_mfcc_cpp(SEXP audio_obj, int n_mfcc, int n_mels, double windowShift, double windowSize, double fmin, double fmax, int lifter, double floor, bool verbose);
RcppExport SEXP _superassp_sptk_mfcc_cpp(SEXP audio_objSEXP, SEXP n_mfccSEXP, SEXP n_melsSEXP, SEXP windowShiftSEXP, SEXP windowSizeSEXP, SEXP fminSEXP, SEXP fmaxSEXP, SEXP lifterSEXP, SEXP floorSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< int >::type n_mfcc(n_mfccSEXP);
    Rcpp::traits::input_parameter< int >::type n_mels(n_melsSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type windowSize(windowSizeSEXP);
    Rcpp::traits::input_parameter< double >::type fmin(fminSEXP);
    Rcpp::traits::input_parameter< double >::type fmax(fmaxSEXP);
    Rcpp::traits::input_parameter< int >::type lifter(lifterSEXP);
    Rcpp::traits::input_parameter< double >::type floor(floorSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sptk_mfcc_cpp(audio_obj, n_mfcc, n_mels, windowShift, windowSize, fmin, fmax, lifter, floor, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rapt_cpp
List rapt_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_rapt_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rapt_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// swipe_cpp
List swipe_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_swipe_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(swipe_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// reaper_cpp
List reaper_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_reaper_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(reaper_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dio_cpp
List dio_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_dio_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dio_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// harvest_cpp
List harvest_cpp(SEXP audio_obj, double minF, double maxF, double windowShift, double voicing_threshold, bool verbose);
RcppExport SEXP _superassp_harvest_cpp(SEXP audio_objSEXP, SEXP minFSEXP, SEXP maxFSEXP, SEXP windowShiftSEXP, SEXP voicing_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type audio_obj(audio_objSEXP);
    Rcpp::traits::input_parameter< double >::type minF(minFSEXP);
    Rcpp::traits::input_parameter< double >::type maxF(maxFSEXP);
    Rcpp::traits::input_parameter< double >::type windowShift(windowShiftSEXP);
    Rcpp::traits::input_parameter< double >::type voicing_threshold(voicing_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(harvest_cpp(audio_obj, minF, maxF, windowShift, voicing_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
