#' Compute the emobase openSMILE feature set
#'
#' This function applies the emobase openSMILE \insertCite{Eyben:2010fq}{superassp} configuration to compute 988
#'  acoustic features reasoned to be part of perception of emotion.
#'
#'
#' @param listOfFiles The full path to the sound file.
#' @param beginTime The starting time of the section of the sound files that
#'   should be analysed.
#' @param endTime The end time of the section of the sound files that should be
#'   analysed.
#' @param explicitExt The file extension of the slice file where the results
#'   should be stored.
#' @param use_cpp Use C++ implementation (default: TRUE, faster). Set to FALSE for Python implementation.
#'
#' @return A list of 988 acoustic values, with the names as reported by
#'   openSMILE. 
#' 
#'   
#' @export
#'
#' @references \insertAllCited{}
lst_emobase <- function(listOfFiles,
                   beginTime=0,
                   endTime=0,
                   explicitExt="ocp",
                   use_cpp = TRUE){
  
  # Use C++ implementation if available and requested
  if (use_cpp) {
    return(lst_emobase_cpp(listOfFiles, beginTime = beginTime,
                          endTime = endTime, verbose = FALSE))
  }
  
  # Python implementation (fallback)
  return(lst_emobase_python(listOfFiles, beginTime = beginTime,
                           endTime = endTime, explicitExt = explicitExt))
}

#' Compute the emobase openSMILE feature set (Python Implementation)
#'
#' Python implementation - used as fallback
#' @keywords internal
lst_emobase_python <- function(listOfFiles,
                   beginTime=0,
                   endTime=0,
                   explicitExt="ocp"){
  
  origSoundFile <- normalizePath(listOfFiles,mustWork = TRUE)
  if(! file.exists(origSoundFile)){
    stop("Unable to open sound file '",listOfFiles,"'.")
  }
  if(endTime == 0){
    endTime <- NULL
  } 
  if(beginTime == 0){
    beginTime <- NULL
  } 
  
  
  py$soundFile <- reticulate::r_to_py(origSoundFile)
  py$beginTime <- reticulate::r_to_py(beginTime)
  py$endTime <- reticulate::r_to_py(endTime)
  
  
  reticulate::py_run_string("import opensmile\
import numpy as np\
\
smile = opensmile.Smile(\
    feature_set=opensmile.FeatureSet.emobase,\
    feature_level=opensmile.FeatureLevel.Functionals,\
)\
\
smile_results = smile.process_file(file=soundFile,\
	start=beginTime,\
	end=endTime)\
\
del soundFile\
gc.collect()")
  
  out <- py$smile_results
  
  return(as.list(out))
  
}

attr(lst_emobase,"ext") <-  c("emo") 
attr(lst_emobase,"outputType") <-  c("list")
attr(lst_emobase,"tracks") <- c("pcm_intensity_sma_max", "pcm_intensity_sma_min", "pcm_intensity_sma_range", 
                            "pcm_intensity_sma_maxPos", "pcm_intensity_sma_minPos", "pcm_intensity_sma_amean", 
                            "pcm_intensity_sma_linregc1", "pcm_intensity_sma_linregc2", "pcm_intensity_sma_linregerrA", 
                            "pcm_intensity_sma_linregerrQ", "pcm_intensity_sma_stddev", "pcm_intensity_sma_skewness", 
                            "pcm_intensity_sma_kurtosis", "pcm_intensity_sma_quartile1", 
                            "pcm_intensity_sma_quartile2", "pcm_intensity_sma_quartile3", 
                            "pcm_intensity_sma_iqr1-2", "pcm_intensity_sma_iqr2-3", "pcm_intensity_sma_iqr1-3", 
                            "pcm_loudness_sma_max", "pcm_loudness_sma_min", "pcm_loudness_sma_range", 
                            "pcm_loudness_sma_maxPos", "pcm_loudness_sma_minPos", "pcm_loudness_sma_amean", 
                            "pcm_loudness_sma_linregc1", "pcm_loudness_sma_linregc2", "pcm_loudness_sma_linregerrA", 
                            "pcm_loudness_sma_linregerrQ", "pcm_loudness_sma_stddev", "pcm_loudness_sma_skewness", 
                            "pcm_loudness_sma_kurtosis", "pcm_loudness_sma_quartile1", "pcm_loudness_sma_quartile2", 
                            "pcm_loudness_sma_quartile3", "pcm_loudness_sma_iqr1-2", "pcm_loudness_sma_iqr2-3", 
                            "pcm_loudness_sma_iqr1-3", "mfcc_sma[1]_max", "mfcc_sma[1]_min", 
                            "mfcc_sma[1]_range", "mfcc_sma[1]_maxPos", "mfcc_sma[1]_minPos", 
                            "mfcc_sma[1]_amean", "mfcc_sma[1]_linregc1", "mfcc_sma[1]_linregc2", 
                            "mfcc_sma[1]_linregerrA", "mfcc_sma[1]_linregerrQ", "mfcc_sma[1]_stddev", 
                            "mfcc_sma[1]_skewness", "mfcc_sma[1]_kurtosis", "mfcc_sma[1]_quartile1", 
                            "mfcc_sma[1]_quartile2", "mfcc_sma[1]_quartile3", "mfcc_sma[1]_iqr1-2", 
                            "mfcc_sma[1]_iqr2-3", "mfcc_sma[1]_iqr1-3", "mfcc_sma[2]_max", 
                            "mfcc_sma[2]_min", "mfcc_sma[2]_range", "mfcc_sma[2]_maxPos", 
                            "mfcc_sma[2]_minPos", "mfcc_sma[2]_amean", "mfcc_sma[2]_linregc1", 
                            "mfcc_sma[2]_linregc2", "mfcc_sma[2]_linregerrA", "mfcc_sma[2]_linregerrQ", 
                            "mfcc_sma[2]_stddev", "mfcc_sma[2]_skewness", "mfcc_sma[2]_kurtosis", 
                            "mfcc_sma[2]_quartile1", "mfcc_sma[2]_quartile2", "mfcc_sma[2]_quartile3", 
                            "mfcc_sma[2]_iqr1-2", "mfcc_sma[2]_iqr2-3", "mfcc_sma[2]_iqr1-3", 
                            "mfcc_sma[3]_max", "mfcc_sma[3]_min", "mfcc_sma[3]_range", "mfcc_sma[3]_maxPos", 
                            "mfcc_sma[3]_minPos", "mfcc_sma[3]_amean", "mfcc_sma[3]_linregc1", 
                            "mfcc_sma[3]_linregc2", "mfcc_sma[3]_linregerrA", "mfcc_sma[3]_linregerrQ", 
                            "mfcc_sma[3]_stddev", "mfcc_sma[3]_skewness", "mfcc_sma[3]_kurtosis", 
                            "mfcc_sma[3]_quartile1", "mfcc_sma[3]_quartile2", "mfcc_sma[3]_quartile3", 
                            "mfcc_sma[3]_iqr1-2", "mfcc_sma[3]_iqr2-3", "mfcc_sma[3]_iqr1-3", 
                            "mfcc_sma[4]_max", "mfcc_sma[4]_min", "mfcc_sma[4]_range", "mfcc_sma[4]_maxPos", 
                            "mfcc_sma[4]_minPos", "mfcc_sma[4]_amean", "mfcc_sma[4]_linregc1", 
                            "mfcc_sma[4]_linregc2", "mfcc_sma[4]_linregerrA", "mfcc_sma[4]_linregerrQ", 
                            "mfcc_sma[4]_stddev", "mfcc_sma[4]_skewness", "mfcc_sma[4]_kurtosis", 
                            "mfcc_sma[4]_quartile1", "mfcc_sma[4]_quartile2", "mfcc_sma[4]_quartile3", 
                            "mfcc_sma[4]_iqr1-2", "mfcc_sma[4]_iqr2-3", "mfcc_sma[4]_iqr1-3", 
                            "mfcc_sma[5]_max", "mfcc_sma[5]_min", "mfcc_sma[5]_range", "mfcc_sma[5]_maxPos", 
                            "mfcc_sma[5]_minPos", "mfcc_sma[5]_amean", "mfcc_sma[5]_linregc1", 
                            "mfcc_sma[5]_linregc2", "mfcc_sma[5]_linregerrA", "mfcc_sma[5]_linregerrQ", 
                            "mfcc_sma[5]_stddev", "mfcc_sma[5]_skewness", "mfcc_sma[5]_kurtosis", 
                            "mfcc_sma[5]_quartile1", "mfcc_sma[5]_quartile2", "mfcc_sma[5]_quartile3", 
                            "mfcc_sma[5]_iqr1-2", "mfcc_sma[5]_iqr2-3", "mfcc_sma[5]_iqr1-3", 
                            "mfcc_sma[6]_max", "mfcc_sma[6]_min", "mfcc_sma[6]_range", "mfcc_sma[6]_maxPos", 
                            "mfcc_sma[6]_minPos", "mfcc_sma[6]_amean", "mfcc_sma[6]_linregc1", 
                            "mfcc_sma[6]_linregc2", "mfcc_sma[6]_linregerrA", "mfcc_sma[6]_linregerrQ", 
                            "mfcc_sma[6]_stddev", "mfcc_sma[6]_skewness", "mfcc_sma[6]_kurtosis", 
                            "mfcc_sma[6]_quartile1", "mfcc_sma[6]_quartile2", "mfcc_sma[6]_quartile3", 
                            "mfcc_sma[6]_iqr1-2", "mfcc_sma[6]_iqr2-3", "mfcc_sma[6]_iqr1-3", 
                            "mfcc_sma[7]_max", "mfcc_sma[7]_min", "mfcc_sma[7]_range", "mfcc_sma[7]_maxPos", 
                            "mfcc_sma[7]_minPos", "mfcc_sma[7]_amean", "mfcc_sma[7]_linregc1", 
                            "mfcc_sma[7]_linregc2", "mfcc_sma[7]_linregerrA", "mfcc_sma[7]_linregerrQ", 
                            "mfcc_sma[7]_stddev", "mfcc_sma[7]_skewness", "mfcc_sma[7]_kurtosis", 
                            "mfcc_sma[7]_quartile1", "mfcc_sma[7]_quartile2", "mfcc_sma[7]_quartile3", 
                            "mfcc_sma[7]_iqr1-2", "mfcc_sma[7]_iqr2-3", "mfcc_sma[7]_iqr1-3", 
                            "mfcc_sma[8]_max", "mfcc_sma[8]_min", "mfcc_sma[8]_range", "mfcc_sma[8]_maxPos", 
                            "mfcc_sma[8]_minPos", "mfcc_sma[8]_amean", "mfcc_sma[8]_linregc1", 
                            "mfcc_sma[8]_linregc2", "mfcc_sma[8]_linregerrA", "mfcc_sma[8]_linregerrQ", 
                            "mfcc_sma[8]_stddev", "mfcc_sma[8]_skewness", "mfcc_sma[8]_kurtosis", 
                            "mfcc_sma[8]_quartile1", "mfcc_sma[8]_quartile2", "mfcc_sma[8]_quartile3", 
                            "mfcc_sma[8]_iqr1-2", "mfcc_sma[8]_iqr2-3", "mfcc_sma[8]_iqr1-3", 
                            "mfcc_sma[9]_max", "mfcc_sma[9]_min", "mfcc_sma[9]_range", "mfcc_sma[9]_maxPos", 
                            "mfcc_sma[9]_minPos", "mfcc_sma[9]_amean", "mfcc_sma[9]_linregc1", 
                            "mfcc_sma[9]_linregc2", "mfcc_sma[9]_linregerrA", "mfcc_sma[9]_linregerrQ", 
                            "mfcc_sma[9]_stddev", "mfcc_sma[9]_skewness", "mfcc_sma[9]_kurtosis", 
                            "mfcc_sma[9]_quartile1", "mfcc_sma[9]_quartile2", "mfcc_sma[9]_quartile3", 
                            "mfcc_sma[9]_iqr1-2", "mfcc_sma[9]_iqr2-3", "mfcc_sma[9]_iqr1-3", 
                            "mfcc_sma[10]_max", "mfcc_sma[10]_min", "mfcc_sma[10]_range", 
                            "mfcc_sma[10]_maxPos", "mfcc_sma[10]_minPos", "mfcc_sma[10]_amean", 
                            "mfcc_sma[10]_linregc1", "mfcc_sma[10]_linregc2", "mfcc_sma[10]_linregerrA", 
                            "mfcc_sma[10]_linregerrQ", "mfcc_sma[10]_stddev", "mfcc_sma[10]_skewness", 
                            "mfcc_sma[10]_kurtosis", "mfcc_sma[10]_quartile1", "mfcc_sma[10]_quartile2", 
                            "mfcc_sma[10]_quartile3", "mfcc_sma[10]_iqr1-2", "mfcc_sma[10]_iqr2-3", 
                            "mfcc_sma[10]_iqr1-3", "mfcc_sma[11]_max", "mfcc_sma[11]_min", 
                            "mfcc_sma[11]_range", "mfcc_sma[11]_maxPos", "mfcc_sma[11]_minPos", 
                            "mfcc_sma[11]_amean", "mfcc_sma[11]_linregc1", "mfcc_sma[11]_linregc2", 
                            "mfcc_sma[11]_linregerrA", "mfcc_sma[11]_linregerrQ", "mfcc_sma[11]_stddev", 
                            "mfcc_sma[11]_skewness", "mfcc_sma[11]_kurtosis", "mfcc_sma[11]_quartile1", 
                            "mfcc_sma[11]_quartile2", "mfcc_sma[11]_quartile3", "mfcc_sma[11]_iqr1-2", 
                            "mfcc_sma[11]_iqr2-3", "mfcc_sma[11]_iqr1-3", "mfcc_sma[12]_max", 
                            "mfcc_sma[12]_min", "mfcc_sma[12]_range", "mfcc_sma[12]_maxPos", 
                            "mfcc_sma[12]_minPos", "mfcc_sma[12]_amean", "mfcc_sma[12]_linregc1", 
                            "mfcc_sma[12]_linregc2", "mfcc_sma[12]_linregerrA", "mfcc_sma[12]_linregerrQ", 
                            "mfcc_sma[12]_stddev", "mfcc_sma[12]_skewness", "mfcc_sma[12]_kurtosis", 
                            "mfcc_sma[12]_quartile1", "mfcc_sma[12]_quartile2", "mfcc_sma[12]_quartile3", 
                            "mfcc_sma[12]_iqr1-2", "mfcc_sma[12]_iqr2-3", "mfcc_sma[12]_iqr1-3", 
                            "lspFreq_sma[0]_max", "lspFreq_sma[0]_min", "lspFreq_sma[0]_range", 
                            "lspFreq_sma[0]_maxPos", "lspFreq_sma[0]_minPos", "lspFreq_sma[0]_amean", 
                            "lspFreq_sma[0]_linregc1", "lspFreq_sma[0]_linregc2", "lspFreq_sma[0]_linregerrA", 
                            "lspFreq_sma[0]_linregerrQ", "lspFreq_sma[0]_stddev", "lspFreq_sma[0]_skewness", 
                            "lspFreq_sma[0]_kurtosis", "lspFreq_sma[0]_quartile1", "lspFreq_sma[0]_quartile2", 
                            "lspFreq_sma[0]_quartile3", "lspFreq_sma[0]_iqr1-2", "lspFreq_sma[0]_iqr2-3", 
                            "lspFreq_sma[0]_iqr1-3", "lspFreq_sma[1]_max", "lspFreq_sma[1]_min", 
                            "lspFreq_sma[1]_range", "lspFreq_sma[1]_maxPos", "lspFreq_sma[1]_minPos", 
                            "lspFreq_sma[1]_amean", "lspFreq_sma[1]_linregc1", "lspFreq_sma[1]_linregc2", 
                            "lspFreq_sma[1]_linregerrA", "lspFreq_sma[1]_linregerrQ", "lspFreq_sma[1]_stddev", 
                            "lspFreq_sma[1]_skewness", "lspFreq_sma[1]_kurtosis", "lspFreq_sma[1]_quartile1", 
                            "lspFreq_sma[1]_quartile2", "lspFreq_sma[1]_quartile3", "lspFreq_sma[1]_iqr1-2", 
                            "lspFreq_sma[1]_iqr2-3", "lspFreq_sma[1]_iqr1-3", "lspFreq_sma[2]_max", 
                            "lspFreq_sma[2]_min", "lspFreq_sma[2]_range", "lspFreq_sma[2]_maxPos", 
                            "lspFreq_sma[2]_minPos", "lspFreq_sma[2]_amean", "lspFreq_sma[2]_linregc1", 
                            "lspFreq_sma[2]_linregc2", "lspFreq_sma[2]_linregerrA", "lspFreq_sma[2]_linregerrQ", 
                            "lspFreq_sma[2]_stddev", "lspFreq_sma[2]_skewness", "lspFreq_sma[2]_kurtosis", 
                            "lspFreq_sma[2]_quartile1", "lspFreq_sma[2]_quartile2", "lspFreq_sma[2]_quartile3", 
                            "lspFreq_sma[2]_iqr1-2", "lspFreq_sma[2]_iqr2-3", "lspFreq_sma[2]_iqr1-3", 
                            "lspFreq_sma[3]_max", "lspFreq_sma[3]_min", "lspFreq_sma[3]_range", 
                            "lspFreq_sma[3]_maxPos", "lspFreq_sma[3]_minPos", "lspFreq_sma[3]_amean", 
                            "lspFreq_sma[3]_linregc1", "lspFreq_sma[3]_linregc2", "lspFreq_sma[3]_linregerrA", 
                            "lspFreq_sma[3]_linregerrQ", "lspFreq_sma[3]_stddev", "lspFreq_sma[3]_skewness", 
                            "lspFreq_sma[3]_kurtosis", "lspFreq_sma[3]_quartile1", "lspFreq_sma[3]_quartile2", 
                            "lspFreq_sma[3]_quartile3", "lspFreq_sma[3]_iqr1-2", "lspFreq_sma[3]_iqr2-3", 
                            "lspFreq_sma[3]_iqr1-3", "lspFreq_sma[4]_max", "lspFreq_sma[4]_min", 
                            "lspFreq_sma[4]_range", "lspFreq_sma[4]_maxPos", "lspFreq_sma[4]_minPos", 
                            "lspFreq_sma[4]_amean", "lspFreq_sma[4]_linregc1", "lspFreq_sma[4]_linregc2", 
                            "lspFreq_sma[4]_linregerrA", "lspFreq_sma[4]_linregerrQ", "lspFreq_sma[4]_stddev", 
                            "lspFreq_sma[4]_skewness", "lspFreq_sma[4]_kurtosis", "lspFreq_sma[4]_quartile1", 
                            "lspFreq_sma[4]_quartile2", "lspFreq_sma[4]_quartile3", "lspFreq_sma[4]_iqr1-2", 
                            "lspFreq_sma[4]_iqr2-3", "lspFreq_sma[4]_iqr1-3", "lspFreq_sma[5]_max", 
                            "lspFreq_sma[5]_min", "lspFreq_sma[5]_range", "lspFreq_sma[5]_maxPos", 
                            "lspFreq_sma[5]_minPos", "lspFreq_sma[5]_amean", "lspFreq_sma[5]_linregc1", 
                            "lspFreq_sma[5]_linregc2", "lspFreq_sma[5]_linregerrA", "lspFreq_sma[5]_linregerrQ", 
                            "lspFreq_sma[5]_stddev", "lspFreq_sma[5]_skewness", "lspFreq_sma[5]_kurtosis", 
                            "lspFreq_sma[5]_quartile1", "lspFreq_sma[5]_quartile2", "lspFreq_sma[5]_quartile3", 
                            "lspFreq_sma[5]_iqr1-2", "lspFreq_sma[5]_iqr2-3", "lspFreq_sma[5]_iqr1-3", 
                            "lspFreq_sma[6]_max", "lspFreq_sma[6]_min", "lspFreq_sma[6]_range", 
                            "lspFreq_sma[6]_maxPos", "lspFreq_sma[6]_minPos", "lspFreq_sma[6]_amean", 
                            "lspFreq_sma[6]_linregc1", "lspFreq_sma[6]_linregc2", "lspFreq_sma[6]_linregerrA", 
                            "lspFreq_sma[6]_linregerrQ", "lspFreq_sma[6]_stddev", "lspFreq_sma[6]_skewness", 
                            "lspFreq_sma[6]_kurtosis", "lspFreq_sma[6]_quartile1", "lspFreq_sma[6]_quartile2", 
                            "lspFreq_sma[6]_quartile3", "lspFreq_sma[6]_iqr1-2", "lspFreq_sma[6]_iqr2-3", 
                            "lspFreq_sma[6]_iqr1-3", "lspFreq_sma[7]_max", "lspFreq_sma[7]_min", 
                            "lspFreq_sma[7]_range", "lspFreq_sma[7]_maxPos", "lspFreq_sma[7]_minPos", 
                            "lspFreq_sma[7]_amean", "lspFreq_sma[7]_linregc1", "lspFreq_sma[7]_linregc2", 
                            "lspFreq_sma[7]_linregerrA", "lspFreq_sma[7]_linregerrQ", "lspFreq_sma[7]_stddev", 
                            "lspFreq_sma[7]_skewness", "lspFreq_sma[7]_kurtosis", "lspFreq_sma[7]_quartile1", 
                            "lspFreq_sma[7]_quartile2", "lspFreq_sma[7]_quartile3", "lspFreq_sma[7]_iqr1-2", 
                            "lspFreq_sma[7]_iqr2-3", "lspFreq_sma[7]_iqr1-3", "pcm_zcr_sma_max", 
                            "pcm_zcr_sma_min", "pcm_zcr_sma_range", "pcm_zcr_sma_maxPos", 
                            "pcm_zcr_sma_minPos", "pcm_zcr_sma_amean", "pcm_zcr_sma_linregc1", 
                            "pcm_zcr_sma_linregc2", "pcm_zcr_sma_linregerrA", "pcm_zcr_sma_linregerrQ", 
                            "pcm_zcr_sma_stddev", "pcm_zcr_sma_skewness", "pcm_zcr_sma_kurtosis", 
                            "pcm_zcr_sma_quartile1", "pcm_zcr_sma_quartile2", "pcm_zcr_sma_quartile3", 
                            "pcm_zcr_sma_iqr1-2", "pcm_zcr_sma_iqr2-3", "pcm_zcr_sma_iqr1-3", 
                            "voiceProb_sma_max", "voiceProb_sma_min", "voiceProb_sma_range", 
                            "voiceProb_sma_maxPos", "voiceProb_sma_minPos", "voiceProb_sma_amean", 
                            "voiceProb_sma_linregc1", "voiceProb_sma_linregc2", "voiceProb_sma_linregerrA", 
                            "voiceProb_sma_linregerrQ", "voiceProb_sma_stddev", "voiceProb_sma_skewness", 
                            "voiceProb_sma_kurtosis", "voiceProb_sma_quartile1", "voiceProb_sma_quartile2", 
                            "voiceProb_sma_quartile3", "voiceProb_sma_iqr1-2", "voiceProb_sma_iqr2-3", 
                            "voiceProb_sma_iqr1-3", "F0_sma_max", "F0_sma_min", "F0_sma_range", 
                            "F0_sma_maxPos", "F0_sma_minPos", "F0_sma_amean", "F0_sma_linregc1", 
                            "F0_sma_linregc2", "F0_sma_linregerrA", "F0_sma_linregerrQ", 
                            "F0_sma_stddev", "F0_sma_skewness", "F0_sma_kurtosis", "F0_sma_quartile1", 
                            "F0_sma_quartile2", "F0_sma_quartile3", "F0_sma_iqr1-2", "F0_sma_iqr2-3", 
                            "F0_sma_iqr1-3", "F0env_sma_max", "F0env_sma_min", "F0env_sma_range", 
                            "F0env_sma_maxPos", "F0env_sma_minPos", "F0env_sma_amean", "F0env_sma_linregc1", 
                            "F0env_sma_linregc2", "F0env_sma_linregerrA", "F0env_sma_linregerrQ", 
                            "F0env_sma_stddev", "F0env_sma_skewness", "F0env_sma_kurtosis", 
                            "F0env_sma_quartile1", "F0env_sma_quartile2", "F0env_sma_quartile3", 
                            "F0env_sma_iqr1-2", "F0env_sma_iqr2-3", "F0env_sma_iqr1-3", "pcm_intensity_sma_de_max", 
                            "pcm_intensity_sma_de_min", "pcm_intensity_sma_de_range", "pcm_intensity_sma_de_maxPos", 
                            "pcm_intensity_sma_de_minPos", "pcm_intensity_sma_de_amean", 
                            "pcm_intensity_sma_de_linregc1", "pcm_intensity_sma_de_linregc2", 
                            "pcm_intensity_sma_de_linregerrA", "pcm_intensity_sma_de_linregerrQ", 
                            "pcm_intensity_sma_de_stddev", "pcm_intensity_sma_de_skewness", 
                            "pcm_intensity_sma_de_kurtosis", "pcm_intensity_sma_de_quartile1", 
                            "pcm_intensity_sma_de_quartile2", "pcm_intensity_sma_de_quartile3", 
                            "pcm_intensity_sma_de_iqr1-2", "pcm_intensity_sma_de_iqr2-3", 
                            "pcm_intensity_sma_de_iqr1-3", "pcm_loudness_sma_de_max", "pcm_loudness_sma_de_min", 
                            "pcm_loudness_sma_de_range", "pcm_loudness_sma_de_maxPos", "pcm_loudness_sma_de_minPos", 
                            "pcm_loudness_sma_de_amean", "pcm_loudness_sma_de_linregc1", 
                            "pcm_loudness_sma_de_linregc2", "pcm_loudness_sma_de_linregerrA", 
                            "pcm_loudness_sma_de_linregerrQ", "pcm_loudness_sma_de_stddev", 
                            "pcm_loudness_sma_de_skewness", "pcm_loudness_sma_de_kurtosis", 
                            "pcm_loudness_sma_de_quartile1", "pcm_loudness_sma_de_quartile2", 
                            "pcm_loudness_sma_de_quartile3", "pcm_loudness_sma_de_iqr1-2", 
                            "pcm_loudness_sma_de_iqr2-3", "pcm_loudness_sma_de_iqr1-3", "mfcc_sma_de[1]_max", 
                            "mfcc_sma_de[1]_min", "mfcc_sma_de[1]_range", "mfcc_sma_de[1]_maxPos", 
                            "mfcc_sma_de[1]_minPos", "mfcc_sma_de[1]_amean", "mfcc_sma_de[1]_linregc1", 
                            "mfcc_sma_de[1]_linregc2", "mfcc_sma_de[1]_linregerrA", "mfcc_sma_de[1]_linregerrQ", 
                            "mfcc_sma_de[1]_stddev", "mfcc_sma_de[1]_skewness", "mfcc_sma_de[1]_kurtosis", 
                            "mfcc_sma_de[1]_quartile1", "mfcc_sma_de[1]_quartile2", "mfcc_sma_de[1]_quartile3", 
                            "mfcc_sma_de[1]_iqr1-2", "mfcc_sma_de[1]_iqr2-3", "mfcc_sma_de[1]_iqr1-3", 
                            "mfcc_sma_de[2]_max", "mfcc_sma_de[2]_min", "mfcc_sma_de[2]_range", 
                            "mfcc_sma_de[2]_maxPos", "mfcc_sma_de[2]_minPos", "mfcc_sma_de[2]_amean", 
                            "mfcc_sma_de[2]_linregc1", "mfcc_sma_de[2]_linregc2", "mfcc_sma_de[2]_linregerrA", 
                            "mfcc_sma_de[2]_linregerrQ", "mfcc_sma_de[2]_stddev", "mfcc_sma_de[2]_skewness", 
                            "mfcc_sma_de[2]_kurtosis", "mfcc_sma_de[2]_quartile1", "mfcc_sma_de[2]_quartile2", 
                            "mfcc_sma_de[2]_quartile3", "mfcc_sma_de[2]_iqr1-2", "mfcc_sma_de[2]_iqr2-3", 
                            "mfcc_sma_de[2]_iqr1-3", "mfcc_sma_de[3]_max", "mfcc_sma_de[3]_min", 
                            "mfcc_sma_de[3]_range", "mfcc_sma_de[3]_maxPos", "mfcc_sma_de[3]_minPos", 
                            "mfcc_sma_de[3]_amean", "mfcc_sma_de[3]_linregc1", "mfcc_sma_de[3]_linregc2", 
                            "mfcc_sma_de[3]_linregerrA", "mfcc_sma_de[3]_linregerrQ", "mfcc_sma_de[3]_stddev", 
                            "mfcc_sma_de[3]_skewness", "mfcc_sma_de[3]_kurtosis", "mfcc_sma_de[3]_quartile1", 
                            "mfcc_sma_de[3]_quartile2", "mfcc_sma_de[3]_quartile3", "mfcc_sma_de[3]_iqr1-2", 
                            "mfcc_sma_de[3]_iqr2-3", "mfcc_sma_de[3]_iqr1-3", "mfcc_sma_de[4]_max", 
                            "mfcc_sma_de[4]_min", "mfcc_sma_de[4]_range", "mfcc_sma_de[4]_maxPos", 
                            "mfcc_sma_de[4]_minPos", "mfcc_sma_de[4]_amean", "mfcc_sma_de[4]_linregc1", 
                            "mfcc_sma_de[4]_linregc2", "mfcc_sma_de[4]_linregerrA", "mfcc_sma_de[4]_linregerrQ", 
                            "mfcc_sma_de[4]_stddev", "mfcc_sma_de[4]_skewness", "mfcc_sma_de[4]_kurtosis", 
                            "mfcc_sma_de[4]_quartile1", "mfcc_sma_de[4]_quartile2", "mfcc_sma_de[4]_quartile3", 
                            "mfcc_sma_de[4]_iqr1-2", "mfcc_sma_de[4]_iqr2-3", "mfcc_sma_de[4]_iqr1-3", 
                            "mfcc_sma_de[5]_max", "mfcc_sma_de[5]_min", "mfcc_sma_de[5]_range", 
                            "mfcc_sma_de[5]_maxPos", "mfcc_sma_de[5]_minPos", "mfcc_sma_de[5]_amean", 
                            "mfcc_sma_de[5]_linregc1", "mfcc_sma_de[5]_linregc2", "mfcc_sma_de[5]_linregerrA", 
                            "mfcc_sma_de[5]_linregerrQ", "mfcc_sma_de[5]_stddev", "mfcc_sma_de[5]_skewness", 
                            "mfcc_sma_de[5]_kurtosis", "mfcc_sma_de[5]_quartile1", "mfcc_sma_de[5]_quartile2", 
                            "mfcc_sma_de[5]_quartile3", "mfcc_sma_de[5]_iqr1-2", "mfcc_sma_de[5]_iqr2-3", 
                            "mfcc_sma_de[5]_iqr1-3", "mfcc_sma_de[6]_max", "mfcc_sma_de[6]_min", 
                            "mfcc_sma_de[6]_range", "mfcc_sma_de[6]_maxPos", "mfcc_sma_de[6]_minPos", 
                            "mfcc_sma_de[6]_amean", "mfcc_sma_de[6]_linregc1", "mfcc_sma_de[6]_linregc2", 
                            "mfcc_sma_de[6]_linregerrA", "mfcc_sma_de[6]_linregerrQ", "mfcc_sma_de[6]_stddev", 
                            "mfcc_sma_de[6]_skewness", "mfcc_sma_de[6]_kurtosis", "mfcc_sma_de[6]_quartile1", 
                            "mfcc_sma_de[6]_quartile2", "mfcc_sma_de[6]_quartile3", "mfcc_sma_de[6]_iqr1-2", 
                            "mfcc_sma_de[6]_iqr2-3", "mfcc_sma_de[6]_iqr1-3", "mfcc_sma_de[7]_max", 
                            "mfcc_sma_de[7]_min", "mfcc_sma_de[7]_range", "mfcc_sma_de[7]_maxPos", 
                            "mfcc_sma_de[7]_minPos", "mfcc_sma_de[7]_amean", "mfcc_sma_de[7]_linregc1", 
                            "mfcc_sma_de[7]_linregc2", "mfcc_sma_de[7]_linregerrA", "mfcc_sma_de[7]_linregerrQ", 
                            "mfcc_sma_de[7]_stddev", "mfcc_sma_de[7]_skewness", "mfcc_sma_de[7]_kurtosis", 
                            "mfcc_sma_de[7]_quartile1", "mfcc_sma_de[7]_quartile2", "mfcc_sma_de[7]_quartile3", 
                            "mfcc_sma_de[7]_iqr1-2", "mfcc_sma_de[7]_iqr2-3", "mfcc_sma_de[7]_iqr1-3", 
                            "mfcc_sma_de[8]_max", "mfcc_sma_de[8]_min", "mfcc_sma_de[8]_range", 
                            "mfcc_sma_de[8]_maxPos", "mfcc_sma_de[8]_minPos", "mfcc_sma_de[8]_amean", 
                            "mfcc_sma_de[8]_linregc1", "mfcc_sma_de[8]_linregc2", "mfcc_sma_de[8]_linregerrA", 
                            "mfcc_sma_de[8]_linregerrQ", "mfcc_sma_de[8]_stddev", "mfcc_sma_de[8]_skewness", 
                            "mfcc_sma_de[8]_kurtosis", "mfcc_sma_de[8]_quartile1", "mfcc_sma_de[8]_quartile2", 
                            "mfcc_sma_de[8]_quartile3", "mfcc_sma_de[8]_iqr1-2", "mfcc_sma_de[8]_iqr2-3", 
                            "mfcc_sma_de[8]_iqr1-3", "mfcc_sma_de[9]_max", "mfcc_sma_de[9]_min", 
                            "mfcc_sma_de[9]_range", "mfcc_sma_de[9]_maxPos", "mfcc_sma_de[9]_minPos", 
                            "mfcc_sma_de[9]_amean", "mfcc_sma_de[9]_linregc1", "mfcc_sma_de[9]_linregc2", 
                            "mfcc_sma_de[9]_linregerrA", "mfcc_sma_de[9]_linregerrQ", "mfcc_sma_de[9]_stddev", 
                            "mfcc_sma_de[9]_skewness", "mfcc_sma_de[9]_kurtosis", "mfcc_sma_de[9]_quartile1", 
                            "mfcc_sma_de[9]_quartile2", "mfcc_sma_de[9]_quartile3", "mfcc_sma_de[9]_iqr1-2", 
                            "mfcc_sma_de[9]_iqr2-3", "mfcc_sma_de[9]_iqr1-3", "mfcc_sma_de[10]_max", 
                            "mfcc_sma_de[10]_min", "mfcc_sma_de[10]_range", "mfcc_sma_de[10]_maxPos", 
                            "mfcc_sma_de[10]_minPos", "mfcc_sma_de[10]_amean", "mfcc_sma_de[10]_linregc1", 
                            "mfcc_sma_de[10]_linregc2", "mfcc_sma_de[10]_linregerrA", "mfcc_sma_de[10]_linregerrQ", 
                            "mfcc_sma_de[10]_stddev", "mfcc_sma_de[10]_skewness", "mfcc_sma_de[10]_kurtosis", 
                            "mfcc_sma_de[10]_quartile1", "mfcc_sma_de[10]_quartile2", "mfcc_sma_de[10]_quartile3", 
                            "mfcc_sma_de[10]_iqr1-2", "mfcc_sma_de[10]_iqr2-3", "mfcc_sma_de[10]_iqr1-3", 
                            "mfcc_sma_de[11]_max", "mfcc_sma_de[11]_min", "mfcc_sma_de[11]_range", 
                            "mfcc_sma_de[11]_maxPos", "mfcc_sma_de[11]_minPos", "mfcc_sma_de[11]_amean", 
                            "mfcc_sma_de[11]_linregc1", "mfcc_sma_de[11]_linregc2", "mfcc_sma_de[11]_linregerrA", 
                            "mfcc_sma_de[11]_linregerrQ", "mfcc_sma_de[11]_stddev", "mfcc_sma_de[11]_skewness", 
                            "mfcc_sma_de[11]_kurtosis", "mfcc_sma_de[11]_quartile1", "mfcc_sma_de[11]_quartile2", 
                            "mfcc_sma_de[11]_quartile3", "mfcc_sma_de[11]_iqr1-2", "mfcc_sma_de[11]_iqr2-3", 
                            "mfcc_sma_de[11]_iqr1-3", "mfcc_sma_de[12]_max", "mfcc_sma_de[12]_min", 
                            "mfcc_sma_de[12]_range", "mfcc_sma_de[12]_maxPos", "mfcc_sma_de[12]_minPos", 
                            "mfcc_sma_de[12]_amean", "mfcc_sma_de[12]_linregc1", "mfcc_sma_de[12]_linregc2", 
                            "mfcc_sma_de[12]_linregerrA", "mfcc_sma_de[12]_linregerrQ", "mfcc_sma_de[12]_stddev", 
                            "mfcc_sma_de[12]_skewness", "mfcc_sma_de[12]_kurtosis", "mfcc_sma_de[12]_quartile1", 
                            "mfcc_sma_de[12]_quartile2", "mfcc_sma_de[12]_quartile3", "mfcc_sma_de[12]_iqr1-2", 
                            "mfcc_sma_de[12]_iqr2-3", "mfcc_sma_de[12]_iqr1-3", "lspFreq_sma_de[0]_max", 
                            "lspFreq_sma_de[0]_min", "lspFreq_sma_de[0]_range", "lspFreq_sma_de[0]_maxPos", 
                            "lspFreq_sma_de[0]_minPos", "lspFreq_sma_de[0]_amean", "lspFreq_sma_de[0]_linregc1", 
                            "lspFreq_sma_de[0]_linregc2", "lspFreq_sma_de[0]_linregerrA", 
                            "lspFreq_sma_de[0]_linregerrQ", "lspFreq_sma_de[0]_stddev", "lspFreq_sma_de[0]_skewness", 
                            "lspFreq_sma_de[0]_kurtosis", "lspFreq_sma_de[0]_quartile1", 
                            "lspFreq_sma_de[0]_quartile2", "lspFreq_sma_de[0]_quartile3", 
                            "lspFreq_sma_de[0]_iqr1-2", "lspFreq_sma_de[0]_iqr2-3", "lspFreq_sma_de[0]_iqr1-3", 
                            "lspFreq_sma_de[1]_max", "lspFreq_sma_de[1]_min", "lspFreq_sma_de[1]_range", 
                            "lspFreq_sma_de[1]_maxPos", "lspFreq_sma_de[1]_minPos", "lspFreq_sma_de[1]_amean", 
                            "lspFreq_sma_de[1]_linregc1", "lspFreq_sma_de[1]_linregc2", "lspFreq_sma_de[1]_linregerrA", 
                            "lspFreq_sma_de[1]_linregerrQ", "lspFreq_sma_de[1]_stddev", "lspFreq_sma_de[1]_skewness", 
                            "lspFreq_sma_de[1]_kurtosis", "lspFreq_sma_de[1]_quartile1", 
                            "lspFreq_sma_de[1]_quartile2", "lspFreq_sma_de[1]_quartile3", 
                            "lspFreq_sma_de[1]_iqr1-2", "lspFreq_sma_de[1]_iqr2-3", "lspFreq_sma_de[1]_iqr1-3", 
                            "lspFreq_sma_de[2]_max", "lspFreq_sma_de[2]_min", "lspFreq_sma_de[2]_range", 
                            "lspFreq_sma_de[2]_maxPos", "lspFreq_sma_de[2]_minPos", "lspFreq_sma_de[2]_amean", 
                            "lspFreq_sma_de[2]_linregc1", "lspFreq_sma_de[2]_linregc2", "lspFreq_sma_de[2]_linregerrA", 
                            "lspFreq_sma_de[2]_linregerrQ", "lspFreq_sma_de[2]_stddev", "lspFreq_sma_de[2]_skewness", 
                            "lspFreq_sma_de[2]_kurtosis", "lspFreq_sma_de[2]_quartile1", 
                            "lspFreq_sma_de[2]_quartile2", "lspFreq_sma_de[2]_quartile3", 
                            "lspFreq_sma_de[2]_iqr1-2", "lspFreq_sma_de[2]_iqr2-3", "lspFreq_sma_de[2]_iqr1-3", 
                            "lspFreq_sma_de[3]_max", "lspFreq_sma_de[3]_min", "lspFreq_sma_de[3]_range", 
                            "lspFreq_sma_de[3]_maxPos", "lspFreq_sma_de[3]_minPos", "lspFreq_sma_de[3]_amean", 
                            "lspFreq_sma_de[3]_linregc1", "lspFreq_sma_de[3]_linregc2", "lspFreq_sma_de[3]_linregerrA", 
                            "lspFreq_sma_de[3]_linregerrQ", "lspFreq_sma_de[3]_stddev", "lspFreq_sma_de[3]_skewness", 
                            "lspFreq_sma_de[3]_kurtosis", "lspFreq_sma_de[3]_quartile1", 
                            "lspFreq_sma_de[3]_quartile2", "lspFreq_sma_de[3]_quartile3", 
                            "lspFreq_sma_de[3]_iqr1-2", "lspFreq_sma_de[3]_iqr2-3", "lspFreq_sma_de[3]_iqr1-3", 
                            "lspFreq_sma_de[4]_max", "lspFreq_sma_de[4]_min", "lspFreq_sma_de[4]_range", 
                            "lspFreq_sma_de[4]_maxPos", "lspFreq_sma_de[4]_minPos", "lspFreq_sma_de[4]_amean", 
                            "lspFreq_sma_de[4]_linregc1", "lspFreq_sma_de[4]_linregc2", "lspFreq_sma_de[4]_linregerrA", 
                            "lspFreq_sma_de[4]_linregerrQ", "lspFreq_sma_de[4]_stddev", "lspFreq_sma_de[4]_skewness", 
                            "lspFreq_sma_de[4]_kurtosis", "lspFreq_sma_de[4]_quartile1", 
                            "lspFreq_sma_de[4]_quartile2", "lspFreq_sma_de[4]_quartile3", 
                            "lspFreq_sma_de[4]_iqr1-2", "lspFreq_sma_de[4]_iqr2-3", "lspFreq_sma_de[4]_iqr1-3", 
                            "lspFreq_sma_de[5]_max", "lspFreq_sma_de[5]_min", "lspFreq_sma_de[5]_range", 
                            "lspFreq_sma_de[5]_maxPos", "lspFreq_sma_de[5]_minPos", "lspFreq_sma_de[5]_amean", 
                            "lspFreq_sma_de[5]_linregc1", "lspFreq_sma_de[5]_linregc2", "lspFreq_sma_de[5]_linregerrA", 
                            "lspFreq_sma_de[5]_linregerrQ", "lspFreq_sma_de[5]_stddev", "lspFreq_sma_de[5]_skewness", 
                            "lspFreq_sma_de[5]_kurtosis", "lspFreq_sma_de[5]_quartile1", 
                            "lspFreq_sma_de[5]_quartile2", "lspFreq_sma_de[5]_quartile3", 
                            "lspFreq_sma_de[5]_iqr1-2", "lspFreq_sma_de[5]_iqr2-3", "lspFreq_sma_de[5]_iqr1-3", 
                            "lspFreq_sma_de[6]_max", "lspFreq_sma_de[6]_min", "lspFreq_sma_de[6]_range", 
                            "lspFreq_sma_de[6]_maxPos", "lspFreq_sma_de[6]_minPos", "lspFreq_sma_de[6]_amean", 
                            "lspFreq_sma_de[6]_linregc1", "lspFreq_sma_de[6]_linregc2", "lspFreq_sma_de[6]_linregerrA", 
                            "lspFreq_sma_de[6]_linregerrQ", "lspFreq_sma_de[6]_stddev", "lspFreq_sma_de[6]_skewness", 
                            "lspFreq_sma_de[6]_kurtosis", "lspFreq_sma_de[6]_quartile1", 
                            "lspFreq_sma_de[6]_quartile2", "lspFreq_sma_de[6]_quartile3", 
                            "lspFreq_sma_de[6]_iqr1-2", "lspFreq_sma_de[6]_iqr2-3", "lspFreq_sma_de[6]_iqr1-3", 
                            "lspFreq_sma_de[7]_max", "lspFreq_sma_de[7]_min", "lspFreq_sma_de[7]_range", 
                            "lspFreq_sma_de[7]_maxPos", "lspFreq_sma_de[7]_minPos", "lspFreq_sma_de[7]_amean", 
                            "lspFreq_sma_de[7]_linregc1", "lspFreq_sma_de[7]_linregc2", "lspFreq_sma_de[7]_linregerrA", 
                            "lspFreq_sma_de[7]_linregerrQ", "lspFreq_sma_de[7]_stddev", "lspFreq_sma_de[7]_skewness", 
                            "lspFreq_sma_de[7]_kurtosis", "lspFreq_sma_de[7]_quartile1", 
                            "lspFreq_sma_de[7]_quartile2", "lspFreq_sma_de[7]_quartile3", 
                            "lspFreq_sma_de[7]_iqr1-2", "lspFreq_sma_de[7]_iqr2-3", "lspFreq_sma_de[7]_iqr1-3", 
                            "pcm_zcr_sma_de_max", "pcm_zcr_sma_de_min", "pcm_zcr_sma_de_range", 
                            "pcm_zcr_sma_de_maxPos", "pcm_zcr_sma_de_minPos", "pcm_zcr_sma_de_amean", 
                            "pcm_zcr_sma_de_linregc1", "pcm_zcr_sma_de_linregc2", "pcm_zcr_sma_de_linregerrA", 
                            "pcm_zcr_sma_de_linregerrQ", "pcm_zcr_sma_de_stddev", "pcm_zcr_sma_de_skewness", 
                            "pcm_zcr_sma_de_kurtosis", "pcm_zcr_sma_de_quartile1", "pcm_zcr_sma_de_quartile2", 
                            "pcm_zcr_sma_de_quartile3", "pcm_zcr_sma_de_iqr1-2", "pcm_zcr_sma_de_iqr2-3", 
                            "pcm_zcr_sma_de_iqr1-3", "voiceProb_sma_de_max", "voiceProb_sma_de_min", 
                            "voiceProb_sma_de_range", "voiceProb_sma_de_maxPos", "voiceProb_sma_de_minPos", 
                            "voiceProb_sma_de_amean", "voiceProb_sma_de_linregc1", "voiceProb_sma_de_linregc2", 
                            "voiceProb_sma_de_linregerrA", "voiceProb_sma_de_linregerrQ", 
                            "voiceProb_sma_de_stddev", "voiceProb_sma_de_skewness", "voiceProb_sma_de_kurtosis", 
                            "voiceProb_sma_de_quartile1", "voiceProb_sma_de_quartile2", "voiceProb_sma_de_quartile3", 
                            "voiceProb_sma_de_iqr1-2", "voiceProb_sma_de_iqr2-3", "voiceProb_sma_de_iqr1-3", 
                            "F0_sma_de_max", "F0_sma_de_min", "F0_sma_de_range", "F0_sma_de_maxPos", 
                            "F0_sma_de_minPos", "F0_sma_de_amean", "F0_sma_de_linregc1", 
                            "F0_sma_de_linregc2", "F0_sma_de_linregerrA", "F0_sma_de_linregerrQ", 
                            "F0_sma_de_stddev", "F0_sma_de_skewness", "F0_sma_de_kurtosis", 
                            "F0_sma_de_quartile1", "F0_sma_de_quartile2", "F0_sma_de_quartile3", 
                            "F0_sma_de_iqr1-2", "F0_sma_de_iqr2-3", "F0_sma_de_iqr1-3", "F0env_sma_de_max", 
                            "F0env_sma_de_min", "F0env_sma_de_range", "F0env_sma_de_maxPos", 
                            "F0env_sma_de_minPos", "F0env_sma_de_amean", "F0env_sma_de_linregc1", 
                            "F0env_sma_de_linregc2", "F0env_sma_de_linregerrA", "F0env_sma_de_linregerrQ", 
                            "F0env_sma_de_stddev", "F0env_sma_de_skewness", "F0env_sma_de_kurtosis", 
                            "F0env_sma_de_quartile1", "F0env_sma_de_quartile2", "F0env_sma_de_quartile3", 
                            "F0env_sma_de_iqr1-2", "F0env_sma_de_iqr2-3", "F0env_sma_de_iqr1-3"
)

