# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast file extension extraction
NULL

fast_file_ext <- function(paths) {
    .Call(`_superassp_fast_file_ext`, paths)
}

fast_is_native <- function(extensions, nativeFormats) {
    .Call(`_superassp_fast_is_native`, extensions, nativeFormats)
}

fast_is_lossless <- function(extensions, losslessFormats) {
    .Call(`_superassp_fast_is_lossless`, extensions, losslessFormats)
}

fast_strip_file_protocol <- function(paths) {
    .Call(`_superassp_fast_strip_file_protocol`, paths)
}

fast_recycle_times <- function(times, n) {
    .Call(`_superassp_fast_recycle_times`, times, n)
}

fast_validate_times <- function(beginTimes, endTimes, filenames) {
    .Call(`_superassp_fast_validate_times`, beginTimes, endTimes, filenames)
}

fast_rename_tracks <- function(objList, newNames) {
    .Call(`_superassp_fast_rename_tracks`, objList, newNames)
}

fast_generate_output_paths <- function(inputPaths, outputExt, isNative, convertTimewindow) {
    .Call(`_superassp_fast_generate_output_paths`, inputPaths, outputExt, isNative, convertTimewindow)
}

fast_calculate_conversion_times <- function(beginTimes, endTimes, durations, windowShift, indices) {
    .Call(`_superassp_fast_calculate_conversion_times`, beginTimes, endTimes, durations, windowShift, indices)
}

fast_basename <- function(paths) {
    .Call(`_superassp_fast_basename`, paths)
}

fast_file_path_sans_ext <- function(paths) {
    .Call(`_superassp_fast_file_path_sans_ext`, paths)
}

fast_build_conversion_df <- function(audioPaths, outputPaths, startTimes, totalTimes, indices) {
    .Call(`_superassp_fast_build_conversion_df`, audioPaths, outputPaths, startTimes, totalTimes, indices)
}

fast_check_file_formats <- function(paths, nativeFormats, losslessFormats) {
    .Call(`_superassp_fast_check_file_formats`, paths, nativeFormats, losslessFormats)
}

