# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast file extension extraction
NULL

fast_file_ext <- function(paths) {
    .Call(`_superassp_fast_file_ext`, paths)
}

fast_is_native <- function(extensions, nativeFormats) {
    .Call(`_superassp_fast_is_native`, extensions, nativeFormats)
}

fast_is_lossless <- function(extensions, losslessFormats) {
    .Call(`_superassp_fast_is_lossless`, extensions, losslessFormats)
}

fast_strip_file_protocol <- function(paths) {
    .Call(`_superassp_fast_strip_file_protocol`, paths)
}

fast_recycle_times <- function(times, n) {
    .Call(`_superassp_fast_recycle_times`, times, n)
}

fast_validate_times <- function(beginTimes, endTimes, filenames) {
    .Call(`_superassp_fast_validate_times`, beginTimes, endTimes, filenames)
}

fast_rename_tracks <- function(objList, newNames) {
    .Call(`_superassp_fast_rename_tracks`, objList, newNames)
}

fast_generate_output_paths <- function(inputPaths, outputExt, isNative, convertTimewindow) {
    .Call(`_superassp_fast_generate_output_paths`, inputPaths, outputExt, isNative, convertTimewindow)
}

fast_calculate_conversion_times <- function(beginTimes, endTimes, durations, windowShift, indices) {
    .Call(`_superassp_fast_calculate_conversion_times`, beginTimes, endTimes, durations, windowShift, indices)
}

fast_basename <- function(paths) {
    .Call(`_superassp_fast_basename`, paths)
}

fast_file_path_sans_ext <- function(paths) {
    .Call(`_superassp_fast_file_path_sans_ext`, paths)
}

fast_build_conversion_df <- function(audioPaths, outputPaths, startTimes, totalTimes, indices) {
    .Call(`_superassp_fast_build_conversion_df`, audioPaths, outputPaths, startTimes, totalTimes, indices)
}

fast_check_file_formats <- function(paths, nativeFormats, losslessFormats) {
    .Call(`_superassp_fast_check_file_formats`, paths, nativeFormats, losslessFormats)
}

estk_pda_cpp <- function(audio_obj, minF = 40.0, maxF = 400.0, windowShift = 5.0, windowSize = 10.0, decimation = 4L, noise_floor = 120L, min_v2uv_coef_thresh = 0.75, v2uv_coef_thresh_ratio = 0.85, uv2v_coef_thresh = 0.88, anti_doubling_thresh = 0.77, peak_tracking = FALSE, verbose = FALSE) {
    .Call(`_superassp_estk_pda_cpp`, audio_obj, minF, maxF, windowShift, windowSize, decimation, noise_floor, min_v2uv_coef_thresh, v2uv_coef_thresh_ratio, uv2v_coef_thresh, anti_doubling_thresh, peak_tracking, verbose)
}

#' ESTK Pitchmark - Find glottal closure instants (C++ implementation)
#'
#' This function implements the Edinburgh Speech Tools pitchmark algorithm
#' for finding instants of glottal closure in laryngograph (EGG) waveforms.
#' This is a lightweight C++ implementation that works directly with AsspDataObj
#' structures for efficient in-memory processing.
#'
#' @param audio_obj AsspDataObj containing audio data
#' @param lx_low_frequency Low pass cutoff frequency for lx filtering (Hz)
#' @param lx_low_order Order of low pass lx filter
#' @param lx_high_frequency High pass cutoff frequency for lx filtering (Hz)
#' @param lx_high_order Order of high pass lx filter
#' @param df_low_frequency Low pass cutoff for differentiated signal (Hz)
#' @param df_low_order Order of low pass filter for differentiated signal
#' @param median_order Order of mean smoother (not median in this implementation)
#' @param fill Insert/remove pitchmarks based on min/max/def periods
#' @param min_period Minimum allowed pitch period in seconds
#' @param max_period Maximum allowed pitch period in seconds
#' @param def_period Default pitch period for unvoiced sections in seconds
#' @param invert Invert polarity of signal
#' @param to_f0 Convert pitchmarks to F0 track
#' @param verbose Show processing messages
#'
#' @return List with pitchmark times and optionally F0 values
#' @export
estk_pitchmark_cpp <- function(audio_obj, lx_low_frequency = 400L, lx_low_order = 19L, lx_high_frequency = 40L, lx_high_order = 19L, df_low_frequency = 1000L, df_low_order = 19L, median_order = 19L, fill = FALSE, min_period = 0.003, max_period = 0.02, def_period = 0.01, invert = FALSE, to_f0 = FALSE, verbose = FALSE) {
    .Call(`_superassp_estk_pitchmark_cpp`, audio_obj, lx_low_frequency, lx_low_order, lx_high_frequency, lx_high_order, df_low_frequency, df_low_order, median_order, fill, min_period, max_period, def_period, invert, to_f0, verbose)
}

#' SPTK Pitch Extraction - Multiple algorithms for F0 estimation
#'
#' This function provides access to four different pitch extraction algorithms
#' from the SPTK (Speech Signal Processing Toolkit):
#' - RAPT: Robust Algorithm for Pitch Tracking (Talkin, 1995)
#' - SWIPE: Sawtooth Waveform Inspired Pitch Estimator (Camacho, 2007)
#' - REAPER: Robust Epoch And Pitch EstimatoR (Google, 2015)
#' - WORLD: DIO algorithm from WORLD vocoder (Morise et al., 2009)
#'
#' @param audio_obj AsspDataObj containing audio data
#' @param algorithm Algorithm to use: "rapt", "swipe", "reaper", or "world"
#' @param minF Lower bound of F0 in Hz (default: 60)
#' @param maxF Upper bound of F0 in Hz (default: 400)
#' @param windowShift Frame shift in milliseconds (default: 10.0)
#' @param voicing_threshold Threshold for voicing decision (algorithm-specific):
#'   - RAPT: correlation threshold, range [-0.6, 0.7], default 0.0
#'   - SWIPE: strength threshold, range [0.2, 0.5], default 0.3
#'   - REAPER: correlation threshold, range [0.0, 1.0], default 0.9
#'   - WORLD: allowed range, range [0.02, 0.2], default 0.1
#' @param verbose Show processing messages (default: FALSE)
#'
#' @return List containing:
#'   - f0: F0 values in Hz (0 for unvoiced frames)
#'   - times: Time points in seconds for each F0 value
#'   - is_voiced: Logical vector indicating voiced frames
#'   - sample_rate: Sample rate of input
#'   - windowShift: Frame shift in milliseconds
#'   - n_frames: Number of frames
#'   - algorithm: Algorithm used
#'
#' @references
#' Talkin, D. (1995). "A robust algorithm for pitch tracking," Speech Coding and Synthesis, 497-518.
#'
#' Camacho, A. (2007). "SWIPE: A sawtooth waveform inspired pitch estimator for speech and music," Doctoral dissertation.
#'
#' Talkin, D. (2015). "REAPER: Robust epoch and pitch estimator," https://github.com/google/REAPER
#'
#' Morise, M., Kawahara, H., & Katayose, H. (2009). "Fast and reliable F0 estimation method," AES 35th International Conference.
#'
#' @export
#' @examples
#' \dontrun{
#' library(superassp)
#' audio <- av_to_asspDataObj("recording.wav")
#'
#' # Extract pitch using RAPT
#' rapt_f0 <- sptk_pitch(audio, algorithm = "rapt")
#'
#' # Extract pitch using SWIPE
#' swipe_f0 <- sptk_pitch(audio, algorithm = "swipe")
#'
#' # Extract pitch using REAPER
#' reaper_f0 <- sptk_pitch(audio, algorithm = "reaper")
#'
#' # Extract pitch using WORLD/DIO
#' world_f0 <- sptk_pitch(audio, algorithm = "world")
#'
#' # Custom F0 range for male voice
#' f0 <- sptk_pitch(audio, algorithm = "rapt", minF = 75, maxF = 200)
#' }
sptk_pitch <- function(audio_obj, algorithm = "rapt", minF = 60.0, maxF = 400.0, windowShift = 10.0, voicing_threshold = -1.0, verbose = FALSE) {
    .Call(`_superassp_sptk_pitch`, audio_obj, algorithm, minF, maxF, windowShift, voicing_threshold, verbose)
}

