# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast file extension extraction
NULL

fast_file_ext <- function(paths) {
    .Call(`_superassp_fast_file_ext`, paths)
}

fast_is_native <- function(extensions, nativeFormats) {
    .Call(`_superassp_fast_is_native`, extensions, nativeFormats)
}

fast_is_lossless <- function(extensions, losslessFormats) {
    .Call(`_superassp_fast_is_lossless`, extensions, losslessFormats)
}

fast_strip_file_protocol <- function(paths) {
    .Call(`_superassp_fast_strip_file_protocol`, paths)
}

fast_recycle_times <- function(times, n) {
    .Call(`_superassp_fast_recycle_times`, times, n)
}

fast_validate_times <- function(beginTimes, endTimes, filenames) {
    .Call(`_superassp_fast_validate_times`, beginTimes, endTimes, filenames)
}

fast_rename_tracks <- function(objList, newNames) {
    .Call(`_superassp_fast_rename_tracks`, objList, newNames)
}

fast_generate_output_paths <- function(inputPaths, outputExt, isNative, convertTimewindow) {
    .Call(`_superassp_fast_generate_output_paths`, inputPaths, outputExt, isNative, convertTimewindow)
}

fast_calculate_conversion_times <- function(beginTimes, endTimes, durations, windowShift, indices) {
    .Call(`_superassp_fast_calculate_conversion_times`, beginTimes, endTimes, durations, windowShift, indices)
}

fast_basename <- function(paths) {
    .Call(`_superassp_fast_basename`, paths)
}

fast_file_path_sans_ext <- function(paths) {
    .Call(`_superassp_fast_file_path_sans_ext`, paths)
}

fast_build_conversion_df <- function(audioPaths, outputPaths, startTimes, totalTimes, indices) {
    .Call(`_superassp_fast_build_conversion_df`, audioPaths, outputPaths, startTimes, totalTimes, indices)
}

fast_check_file_formats <- function(paths, nativeFormats, losslessFormats) {
    .Call(`_superassp_fast_check_file_formats`, paths, nativeFormats, losslessFormats)
}

estk_pda_cpp <- function(audio_obj, minF = 40.0, maxF = 400.0, windowShift = 5.0, windowSize = 10.0, decimation = 4L, noise_floor = 120L, min_v2uv_coef_thresh = 0.75, v2uv_coef_thresh_ratio = 0.85, uv2v_coef_thresh = 0.88, anti_doubling_thresh = 0.77, peak_tracking = FALSE, verbose = FALSE) {
    .Call(`_superassp_estk_pda_cpp`, audio_obj, minF, maxF, windowShift, windowSize, decimation, noise_floor, min_v2uv_coef_thresh, v2uv_coef_thresh_ratio, uv2v_coef_thresh, anti_doubling_thresh, peak_tracking, verbose)
}

#' ESTK Pitchmark - Find glottal closure instants (C++ implementation)
#'
#' This function implements the Edinburgh Speech Tools pitchmark algorithm
#' for finding instants of glottal closure in laryngograph (EGG) waveforms.
#' This is a lightweight C++ implementation that works directly with AsspDataObj
#' structures for efficient in-memory processing.
#'
#' @param audio_obj AsspDataObj containing audio data
#' @param lx_low_frequency Low pass cutoff frequency for lx filtering (Hz)
#' @param lx_low_order Order of low pass lx filter
#' @param lx_high_frequency High pass cutoff frequency for lx filtering (Hz)
#' @param lx_high_order Order of high pass lx filter
#' @param df_low_frequency Low pass cutoff for differentiated signal (Hz)
#' @param df_low_order Order of low pass filter for differentiated signal
#' @param median_order Order of mean smoother (not median in this implementation)
#' @param fill Insert/remove pitchmarks based on min/max/def periods
#' @param min_period Minimum allowed pitch period in seconds
#' @param max_period Maximum allowed pitch period in seconds
#' @param def_period Default pitch period for unvoiced sections in seconds
#' @param invert Invert polarity of signal
#' @param to_f0 Convert pitchmarks to F0 track
#' @param verbose Show processing messages
#'
#' @return List with pitchmark times and optionally F0 values
#' @export
estk_pitchmark_cpp <- function(audio_obj, lx_low_frequency = 400L, lx_low_order = 19L, lx_high_frequency = 40L, lx_high_order = 19L, df_low_frequency = 1000L, df_low_order = 19L, median_order = 19L, fill = FALSE, min_period = 0.003, max_period = 0.02, def_period = 0.01, invert = FALSE, to_f0 = FALSE, verbose = FALSE) {
    .Call(`_superassp_estk_pitchmark_cpp`, audio_obj, lx_low_frequency, lx_low_order, lx_high_frequency, lx_high_order, df_low_frequency, df_low_order, median_order, fill, min_period, max_period, def_period, invert, to_f0, verbose)
}

